import { DepartmentAuthoritySignatoryModel } from "./Master/departmentauthoritysignatory.model";
import { DepartmentReferenceModel } from "./Master/department-reference.model";
import { VCCreationDDLModel } from "./VC/vc-participant-model";
import { OrderTypeMasterModel } from "./orderlist.model";

export class DDLModel {
  constructor() {
    this.ddlCompliantAction = [];
    this.ddlEntry = [];
    this.ddlDepartment = [];
    this.ddlState = [];
    this.ddlService = [];
    this.ddlBeneficiarytype = [];
    this.ddlExecutiveDepartment = [];
    this.ddlConcernedDepartment = [];
    this.ddlNodel = [];
    this.ddlTypeScheme = [];
    this.ddlOrderSector = [];
    this.ddlBeneficiaryCategory = [];
    this.ddlCategoryScheme = [];
    this.ddlOrderType = [];
    this.ddlGenerateOrderType = [];
    this.orderIssueBy = [];
    this.OrderModuleName = [];
    this.ddlModeOfDelivery = [];
    this.ddlSchemeType = [];
    this.ddlCategory = [];
    this.ddPaymentThrough = [];
    this.ddlModeofPayment = [];
    this.ddlPaymentDisbursementMode = [];
    this.ddlSchemeArea = [];
    this.ddlSchemeOutput = [];
    this.ddlOrderRelatedToYear = [];
    this.ddlOrderRelatedToDepartment = [];
    this.ddlSchemeMaster = [];
    this.ddlDistrict = [];
    this.ddlLookUpType = [];
    this.ddlAdvCategory = [];
    this.ddlAdvSubCategory = [];
    this.ddlAdvertisementNotification = [];
    this.ddlUserType = [];
    this.ddlTitle = [];
    this.ddlDesignation = [];
    this.ddlUserGroup = [];
    this.ddlAdminDepartment = [];
    this.ddlDivision = [];
    this.ddlParliamentConstituency = [];
    this.ddlAssemblyConstituency = [];
    this.ddlBlock = [];
    this.ddlTehsil = [];
    this.ddlGender = [];
    this.ddlCommonMaster = [];
    this.ddlSchemeServiceType = [];
    this.ddlSchemeServiceProgramArea = [];
    this.ddlSchemeEligibility = [];
    this.ddlSchemeListOfRequiredDoc = [];
    this.ddlSchemePayFees = [];
    this.ddlSchemeModeOfDisbursement = [];
    this.ddlSchemePaymentDisbursementFrequency = [];
    this.ddlSchemeModeOfDelivery = [];
    this.ddlSchemeListOfOtherDoc = [];
    this.RadioSchemeOwnedBy = [];
    this.RadioRGDPSAct = [];
    this.RadioApplyForScheme = [];
    this.RadioSchemeExpriedOn = [];
    this.RadioSchemeModeofApplying = [];
    this.RadioListOfRequiredDoc = [];
    this.RadioServiceFee = [];
    this.RadioPaymentDisbursementFrequency = [];
    this.RadioMadeOfApplingOnlineAndBoth = [];
    this.ddlSchemeNameOfDocument = [];
    this.ddlOrderModuleName = [];
    this.ddlWidgetMaster = [];
    this.ddlOrderIssueBy = [];
    this.ddlMonitoringParameters = [];
    this.ddlPlatformMaster = [];
    this.RadioIsPushOrIsPull = [];
    this.ddlOffice = [];
    this.ddlNotificationTemplateType = [];
    this.ddlSchemefaqMaster = [];
    this.ddlApplicationType = [];
    this.ddlPageType = [];
    this.ddlApplicationMenu = [];
    this.ddlURLType = [];
    this.ddlReferencee = [];
    this.ddlLMS_LetterAction = [];
    this.ddlVIPLMS_LetterAction = [];
    this.ddlUser = [];
    this.ddlSchemeName = [];
    this.RadioLinkedToScheme = [];
    this.ddlClientModule = [];
    this.ddlUserByAdminDepartment = [];
    this.ddlSchemePageType = [];
    this.ddlMonitoringParameterLookUpType = [];
    this.ddlCitizenLetterAttachment = [];
    this.ddlAuthoritySignatory = [];
    this.ddlCCReference = [];
    this.ddlContactPersonType = [];
    this.ddlAchievementCategory = [];
    this.ddlAchievementSubCategory = [];
    this.ddlOrderSubType = [];
    this.ddlSchemes = [];
    this.ddlGalleryUploadType = [];
    this.RadioSchemeType = [];
    this.ddlCancellationReason = [];
    this.ddlCurrentDateVC = [];
    this.ddlSector = [];
    this.ddlImpCategory = [];
    this.ddlImportantDecisionSubCategory = [];
    this.ddlModuleName = [];
    this.ddlPriorityModule = [];
    this.ddlEntryTypeModule = [];
    this.ddlCompliantFilter = [];
    this.ddluserlist = [];
    this.ddlEntryTypeMaster = [];
    this.ddlDptContactDesignation = [];
    this.ddlSSOId = [];
    this.RadioSchemeService = [];
    this.RadioDepartmentDistrict = [];
    this.ddlDepartmentCategory = [];
    this.ddlJankalyanCategory = [];
    this.ddlProjectStatus = [];
    this.ddlProjectProgram = [];
    this.ddlProjectYearOfInitiation = [];
    this.ddlProjectCategory = [];
    this.ddlProjectSubCategory = [];
    this.ddlNameTitle = [];
    this.RadioProjectsUrbanorRural = [];
    this.ddlMPConstituency = [];
    this.ddlMLAConstituency = [];
    this.ddlProjectMileStoneStatus = [];
    this.ddlProjectMileStone = [];
    this.ddlNewspaperNewsMode = [];
    this.ddlNewspaperNewsType = [];
    this.ddlNewspaperSubject = [];
    this.ddlNewspaperSourceType = [];
    this.ddlNewspaperMaster = [];
    this.ddlNewspaperClassification = [];
    this.ddlNewspaperPublicationType = [];
    this.ddlNewspaperEdition = [];
    this.ddlNewspaperPageNumber = [];
    this.ddlNewspaperProgressNewsType = [];
    this.ddlNewspaperCoverageType = [];
    this.ddlProjectWorkCategory = [];
    this.ddlProjectProgramSchemeType = [];
    this.ddlPageMasterDetails = [];
    this.ddlChildPageDescriptionCategory = [];
    this.ddlCMISReportModules = [];
    this.ddlDepartmentForCMISReport = [];
    this.ddlMLAConstituencyWithDistrictName = [];
    this.ddlCreatedByUserForProject = [];
    this.ddlProjectSubSubCategory = [];
    this.ddlMLAConstituencyWithDesignation = [];
    this.ddlCMISBudgetYear = [];
    this.ddlVCCategory = [];
    this.ddlCMOOfficers = [];
    this.ddlPhysicalUnit = [];
    this.ddlFinancialUnit = [];
    this.ddlKPICategory = [];
    this.ddlYearMaster = [];
    this.ddlPageMasterforCMISCompliance = [];
    this.ddlMonth = [];
    this.ddlComparativeYearGrandTotal = [];
    this.RadioDepartmentCategory = [];
    this.ddlUserDepartment = [];
    this.ddlDepartmentForDistrictKPIList = [];
    this.ddlDepartmentForDepartmentalProgressList = [];
    this.ddlHelpDocTypeOnWebServiceMaster = [];
    this.ddlUserAdminDepartment = [];
    this.ddlComparativeParameterCategory = [];
    this.RadioMenuClassificationType = [];
    this.RadioParameterTargetBased = [];
    this.ddlClassificationPageType = [];
    this.ddlClassification = [];
    this.RadioDepartmentDistrictbutton = [];
    this.ddlDepartmentContactCategory = [];
    this.ddlAdvertisementPopUpCategory = [];
    this.ddlDesignationForPressRelease = [];
    this.ddlCabinetMinister = [];
    this.ddlStateMinister = [];
    this.RadioStateDistrict = [];
    this.ddlCommonCategoryLookup = [];
    this.ddlPressReleaseDepartment = [];
    this.ddlPressReleaseLookupCategory = [];
    this.ddlDepartmentSubMenuList = [];
    this.ddlModuleCategoryList = [];
    this.ddlDepartmentSectionMaster = [];
    this.ddlCreatedByDepartmentMenu = [];
    this.ddlModifiedByUserForDepartmentSectionMapping = [];
    this.ddlModifiedBypressRelease = [];
    this.RadioDepartmentSubMenuShowAsSeparate = [];
    this.RadioDepartmentSubMenuRedirectionManagement = [];
    this.ddlManualType = [];
  }
  RadioDepartmentSubMenuRedirectionManagement: DdlItemModel[];
  ddlModifiedBypressRelease: DdlItemModel[];
  RadioDepartmentSubMenuShowAsSeparate: DdlItemModel[] = [];
  ddlModifiedByUserForDepartmentSectionMapping: DdlItemModel[] = [];
  ddlModifiedByUserForDepartmentSubMenu: DdlItemModel[] = [];
  ddlCreatedByDepartmentMenu: DdlItemModel[];
  ddlDepartmentSectionMaster: DdlItemModel[];
  ddlModuleCategoryList: DdlItemModel[];
  ddlDepartmentSubMenuList: DdlItemModel[];
  ddlPressReleaseLookupCategory: DdlItemModel[];
  ddlCommonCategoryLookup: DdlItemModel[];
  ddlPressReleaseDepartment: DdlItemModel[];
  RadioStateDistrict: DdlItemModel[];
  ddlCabinetMinister: DdlItemModel[];
  ddlStateMinister: DdlItemModel[];
  ddlDesignationForPressRelease: DdlItemModel[];
  ddlAdvertisementPopUpCategory: DdlItemModel[];
  ddlDepartmentContactCategory: DdlItemModel[];
  RadioDepartmentDistrictbutton: DdlItemModel[];
  RadioParameterTargetBased: DdlItemModel[];
  ddlClassification: DdlItemModel[];
  ddlClassificationPageType: DdlItemModel[];
  RadioMenuClassificationType: DdlItemModel[];
  ddlComparativeParameterCategory: DdlItemModel[];
  ddlUserAdminDepartment: DdlItemModel[];
  ddlHelpDocTypeOnWebServiceMaster: DdlItemModel[];
  ddlDepartmentForDistrictKPIList: DdlItemModel[];
  RadioDepartmentCategory: DdlItemModel[];
  ddlDepartmentForDepartmentalProgressList: DdlItemModel[];
  ddlComparativeYearGrandTotal: DdlItemModel[];
  ddlMonth: DdlItemModel[];
  ddlPageMasterforCMISCompliance: DdlItemModel[];
  ddlYearMaster: DdlItemModel[];
  ddlPhysicalUnit: DdlItemModel[];
  ddlFinancialUnit: DdlItemModel[];
  ddlKPICategory: DdlItemModel[];
  ddlCMOOfficers: DdlItemModel[];
  ddlCMISBudgetYear: DdlItemModel[];
  ddlVCCategory: DdlItemModel[];
  ddlMLAConstituencyWithDesignation: DdlItemModel[];
  ddlProjectSubSubCategory: DdlItemModel[];
  ddlCreatedByUserForProject: DdlItemModel[];
  ddlMLAConstituencyWithDistrictName: DdlItemModel[];
  ddlDepartmentForCMISReport: DdlItemModel[];
  ddlCMISReportModules: DdlItemModel[];
  ddlPageMasterDetails: DdlItemModel[];
  ddlChildPageDescriptionCategory: DdlItemModel[];
  ddlProjectProgramSchemeType: DdlItemModel[];
  ddlProjectWorkCategory: DdlItemModel[];
  ddlNewspaperMaster: DdlItemModel[];
  ddlNewspaperClassification: DdlItemModel[];
  ddlNewspaperPublicationType: DdlItemModel[];
  ddlNewspaperEdition: DdlItemModel[];
  ddlNewspaperPageNumber: DdlItemModel[];
  ddlNewspaperProgressNewsType: DdlItemModel[];
  ddlNewspaperCoverageType: DdlItemModel[];
  ddlNewspaperSourceType: DdlItemModel[];
  ddlNewspaperSubject: DdlItemModel[];
  ddlNewspaperNewsMode: DdlItemModel[];
  ddlNewspaperNewsType: DdlItemModel[];
  ddlMLAConstituency: DdlItemModel[];
  ddlMPConstituency: DdlItemModel[];
  ddlProjectMileStoneStatus: DdlItemModel[];
  ddlProjectMileStone: DdlItemModel[];
  ddlProjectStatus: DdlItemModel[];
  ddlProjectProgram: DdlItemModel[];
  ddlProjectYearOfInitiation: DdlItemModel[];
  ddlProjectCategory: DdlItemModel[];
  ddlProjectSubCategory: DdlItemModel[];
  ddlJankalyanCategory: DdlItemModel[];
  ddlDepartmentCategory: DdlItemModel[];
  RadioSchemeService: DdlItemModel[];
  RadioDepartmentDistrict: DdlItemModel[];
  ddlDptContactDesignation: DdlItemModel[];
  ddlEntryTypeMaster: DdlItemModel[];
  OrderWithRequiredType: OrderTypeMasterModel[];
  ddluserlist: DdlItemModel[];
  ddlCompliantFilter: DdlItemModel[];
  ddlCompliantAction: DdlItemModel[];
  ddlModuleName: DdlItemModel[];
  ddlPriorityModule: DdlItemModel[];
  ddlEntryTypeModule: DdlItemModel[];
  ddlImpCategory: DdlItemModel[];
  ddlCurrentDateVC: VCCreationDDLModel[];
  ddlCreateVCList: VCCreationDDLModel[];
  ddlCancellationReason: DdlItemModel[];
  ddlVCType: DdlItemModel[];
  ddlVCMode: DdlItemModel[];
  ddlVCParticipantCategory: DdlItemModel[];
  RadioSchemeType: DdlItemModel[];
  ddlOrderSubType: DdlItemModel[];
  ddlContactPersonType: DdlItemModel[];
  ddlMonitoringParameterLookUpType: DdlItemModel[];
  RadioLinkedToScheme: DdlItemModel[];
  ddlUserByAdminDepartment: DdlItemModel[];
  ddlSchemePageType: DdlItemModel[];
  ddlSchemeName: DdlItemModel[];
  ddlEntry: DdlItemModel[];
  ddlDepartment: DdlItemModel[];
  ddlService: DdlItemModel[];
  ddlBeneficiarytype: DdlItemModel[];
  ddlExecutiveDepartment: DdlItemModel[];
  ddlConcernedDepartment: DdlItemModel[];
  ddlNodel: DdlItemModel[];
  ddlTypeScheme: DdlItemModel[];
  ddlOrderSector: DdlItemModel[];
  ddlBeneficiaryCategory: DdlItemModel[];
  ddlCategoryScheme: DdlItemModel[];
  ddlOrderType: DdlItemModel[];
  ddlGenerateOrderType: DdlItemModel[];
  orderIssueBy: DdlItemModel[];
  OrderModuleName: DdlItemModel[];
  ddlModeOfDelivery: DdlItemModel[];
  ddlSchemeType: DdlItemModel[];
  ddlCategory: DdlItemModel[];
  ddPaymentThrough: DdlItemModel[];
  ddlModeofPayment: DdlItemModel[];
  ddlPaymentDisbursementMode: DdlItemModel[];
  ddlSchemeArea: DdlItemModel[];
  ddlSchemeOutput: DdlItemModel[];
  ddlOrderRelatedToYear: RelatedToDDlModel[];
  ddlOrderRelatedToDepartment: RelatedToDDlModel[];
  ddlSchemeMaster: DdlItemModel[];
  ddlDistrict: DdlItemModel[];
  ddlLookUpType: DdlItemModel[];
  ddlAdvCategory: DdlItemModel[];
  ddlAdvSubCategory: DdlItemModel[];
  ddlAdvertisementNotification: DdlItemModel[];
  ddlUserType: DdlItemModel[];
  ddlTitle: DdlItemModel[];
  ddlDesignation: DdlItemModel[];
  ddlUserGroup: DdlItemModel[];
  ddlAdminDepartment: DdlItemModel[];
  ddlDivision: DdlItemModel[];
  ddlParliamentConstituency: DdlItemModel[];
  ddlAssemblyConstituency: DdlItemModel[];
  ddlBlock: DdlItemModel[];
  ddlTehsil: DdlItemModel[];
  ddlGender: DdlItemModel[];
  ddlCommonMaster: DdlItemModel[];
  ddlSchemeServiceType: DdlItemModel[];
  ddlSchemeServiceProgramArea: DdlItemModel[];
  ddlSchemeEligibility: DdlItemModel[];
  ddlSchemeListOfRequiredDoc: DdlItemModel[];
  ddlSchemePayFees: DdlItemModel[];
  ddlSchemeModeOfDisbursement: DdlItemModel[];
  ddlSchemePaymentDisbursementFrequency: DdlItemModel[];
  ddlSchemeModeOfDelivery: DdlItemModel[];
  ddlSchemeListOfOtherDoc: DdlItemModel[];
  RadioSchemeOwnedBy: DdlItemModel[];
  RadioRGDPSAct: DdlItemModel[];
  RadioApplyForScheme: DdlItemModel[];
  RadioSchemeExpriedOn: DdlItemModel[];
  RadioSchemeModeofApplying: DdlItemModel[];
  RadioListOfRequiredDoc: DdlItemModel[];
  RadioServiceFee: DdlItemModel[];
  RadioPaymentDisbursementFrequency: DdlItemModel[];
  RadioMadeOfApplingOnlineAndBoth: DdlItemModel[];
  ddlSchemeNameOfDocument: DdlItemModel[];
  ddlOrderModuleName: DdlItemModel[];
  ddlWidgetMaster: DdlItemModel[];
  ddlOrderIssueBy: DdlItemModel[];
  ddlMonitoringParameters: DdlItemModel[];
  ddlPlatformMaster: DdlItemModel[];
  RadioIsPushOrIsPull: DdlItemModel[];
  ddlOffice: DdlItemModel[];
  ddlNotificationTemplateType: DdlItemModel[];
  ddlSchemefaqMaster: DdlItemModel[];
  ddlApplicationType: DdlItemModel[];
  ddlPageType: DdlItemModel[];
  ddlApplicationMenu: DdlItemModel[];
  ddlURLType: DdlItemModel[];
  ddlHelpDocType: DdlItemModel[];
  ddlReferencee: DdlItemModel[];
  ddlLMS_LetterAction: DdlItemModel[];
  ddlVIPLMS_LetterAction: DdlItemModel[];
  ddlUser: DdlItemModel[];
  ddlClientModule: DdlItemModel[];
  ddlCitizenLetterAttachment: DdlItemModel[];
  ddlAuthoritySignatory: DepartmentAuthoritySignatoryModel[];
  ddlCCReference: DepartmentReferenceModel[];
  ddlAchievementCategory: DdlItemModel[];
  ddlAchievementSubCategory: DdlItemModel[];
  ddlSchemes: DdlItemModel[];
  ddlGalleryUploadType: DdlItemModel[];
  RadioOfficeType: DdlItemModel[];
  RadioVcLocationType: DdlItemModel[];
  ddlSector: DdlItemModel[];
  ddlImportantDecisionSubCategory: DdlItemModel[];
  ddlState: DdlItemModel[];
  ddlSSOId: DdlItemModel[];
  ddlNameTitle: DdlItemModel[];
  RadioProjectsUrbanorRural: DdlItemModel[];
  ddlUserDepartment: DdlItemModel[];
  ddlPressReleaseCategory: DdlItemModel[] = [];
  ddlManualType: DdlItemModel[];
}

export class FilterDDlModel {
  FilterFor: string;
  Value: any;
  FilterFrom: string;
}

export class DdlItemModel {
  Value: any;
  Text: string;
}
export class ColumnHeaderModel {
  Value: string;
  Text: string;
}

export class DocumentUrlModel {
  Url: string;
  Extension: string;
  DisplayName: string;
  IsNew: boolean;
}

export class RelatedToDDlModel {
  rowno: string;
  particulars: string;
  prj_dept: string;
}

export class CommonLayoutModel {
  Title: string;
  Maticon: string;
  Maticontitle: string;
  Routelink: string;
}

export class CommonIdModel {
  Id: number;
  Paasword: string;
}
