using CMOWebApi.Models.AutoGeneratedModels;
using CMOWebApi.Models.GeneralModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AdminModel
{
    public class UserManagementModel
    {
    }

    public class LoggedInUserDetailViewModel
    {
        public UserViewModel UserViewModel { get; set; }
        public List<AssignedUserPagePermissionViewModel> AssignedUserPagePermissionViewModelList { get; set; }
        public List<UserMenuViewModel> UserMenuViewModelList { get; set; }
        public string Token { get; set; }
    }

    public class UserViewModel
    {
        public int UserId { get; set; }
        public string UserType { get; set; }
        public string Title { get; set; }
        public string UserName { get; set; }
        public string SSOID { get; set; }
        public string Gender { get; set; }
        public string UserEmail { get; set; }
        public string Mobile { get; set; }
        public string IPNo { get; set; }
        public string LandlineNo { get; set; }
        public string ProfilePic { get; set; }
        public bool UserIsActive { get; set; }
        public bool UserIsDeleted { get; set; }
        public Nullable<bool> isUpdateProfileFirstTime { get; set; }
        public System.DateTime UserCreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DesignationCode { get; set; }
        public string DesignationName { get; set; }
        public string DesignationNameHindi { get; set; }
        public Nullable<int> GroupCode { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> OfficeCode { get; set; }
        public string OfficeName { get; set; }
        public string OfficeShortName { get; set; }
        public string CreatedByUserName { get; set; }
        public string ModifiedByUserName { get; set; }
        public string DivisionCodes { get; set; }
        public string DivisionNames { get; set; }
        public List<string> DivisionCodeList { get; set; }
        public string DistrictCodes { get; set; }
        public string DistrictNames { get; set; }
        public List<string> DistrictCodeList { get; set; }
        public string PCCodes { get; set; }
        public string PCNames { get; set; }
        public List<string> PCCodeList { get; set; }
        public string AdminDepartmentCodes { get; set; }
        public string AdminDepartmentNames { get; set; }
        public List<string> AdminDepartmentCodeList { get; set; }
        public string DepartmentCodes { get; set; }
        public string DepartmentNames { get; set; }
        public string DepartmentNamesHindi { get; set; }
        public List<string> DepartmentCodeList { get; set; }
        public string TehsilCodes { get; set; }
        public string TehsilNames { get; set; }
        public List<string> TehsilCodeList { get; set; }
        public string BlockCodes { get; set; }
        public string BlockNames { get; set; }
        public List<string> BlockCodeList { get; set; }
        public string ACCodes { get; set; }
        public string ACNames { get; set; }
        public List<string> ACCodeList { get; set; }
        public string UserTypeTitle { get; set; }
        public long? FileSize { get; set; }
        public string DistrictOffice { get; set; }
        public Nullable<int> SpecificPermissionCount { get; set; }
    }

    public class UserPostModel
    {
        public int UserId { get; set; }
        public string UserType { get; set; }
        [Display(Name = "SSO")]
        [Required(ErrorMessage = "{0} is Required!")]
        public string SSOID { get; set; }
        [Display(Name = "Title")]
        [Required(ErrorMessage = "{0} field is Required!")]
        public string Title { get; set; }
        [Display(Name = "User Name")]
        [Required(ErrorMessage = "{0} field is Required!")]
        public string UserName { get; set; }
        public int? Designation { get; set; }
        [Display(Name = "Gender")]
        [Required(ErrorMessage = "{0} field is Required!")]
        public string Gender { get; set; }

        [Display(Name = "Email")]
        [Required(ErrorMessage = "{0} field is Required!")]
        [EmailAddress]
        [StringLength(100, ErrorMessage = "{0} should not be more than {1} char")]
        public string UserEmail { get; set; }

        [Required]
        [MaxLength(12, ErrorMessage = "{0} should not be more than 16 digit")]
        [MinLength(10, ErrorMessage = "{0} Number should not be less than 9 digit")]
        [Display(Name = "Mobile")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "{0} must be number.")]
        public string Mobile { get; set; }

        [MaxLength(6, ErrorMessage = "{0} should not be more than {1} digit")]
        [Display(Name = "IP No")]
        [RegularExpression("^[0-9]*$", ErrorMessage = "{0} must be number.")]
        public string IPNo { get; set; }

        [MaxLength(50, ErrorMessage = "{0} should not be more than {1} digit")]

        [Display(Name = "Landline No")]
        [RegularExpression("^[0-9]+(?:-[0-9]+)?(,[0-9]+(?:-[0-9]+)?)*$", ErrorMessage = "{0} must be number or ',' or '-'.")]
        public string LandlineNo { get; set; }
        public string ProfilePic { get; set; }
        [Display(Name = "Office Code")]
        [Required(ErrorMessage = "{0} field is Required!")]
        public string OfficeCode { get; set; }
        public int? Group { get; set; }
        public List<string> Department { get; set; }
        public List<string> Division { get; set; }
        //public List<string> District { get; set; }

        public string District { get; set; }
        public List<string> Block { get; set; }
        public List<string> Tehsil { get; set; }

        public List<string> ParConstituancy { get; set; }
        public List<string> AssConstituancy { get; set; }

        public bool UserIsActive { get; set; }
        public bool UserIsDeleted { get; set; }
        public DateTime UserCreateDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public int? CreatedBy { get; set; }
        public int? ModifiedBy { get; set; }
    }
    public  class UserAdminDepartmentViewModel
    {
        public int AdmDepartmentId { get; set; }
        public int AdmDepartmentCode { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public string AdmDepartmentTitleHindi { get; set; }
        public string AdmDepartmentShortTitle { get; set; }
        public string AdmDepartmentShortTitleHindi { get; set; }
        public bool AdmDepartmentIsActive { get; set; }
        public bool AdmDepartmentIsDeleted { get; set; }
        public int UserId { get; set; }
    }
    public class UserDepartmentViewModel
    {
        public Nullable<int> DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public string DepartmentShortTitle { get; set; }
        public string DepartmentShortTitleHindi { get; set; }
        public int AdmDepartmentCode { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public int UserId { get; set; }
		public Nullable<bool> IsVisibleOnFront { get; set; }
        public Nullable<long> DepartmentDistrictCode { get; set; }
        public Nullable<long> CMOOfficerCode { get; set; }
    }

    public class UserOfficeViewModel
    {
        public Nullable<int> OfficeCode { get; set; }
        public string OfficeName { get; set; }
        public string OfficeNameHindi { get; set; }
        public string OfficeShortName { get; set; }
        public string OfficeShortNameHindi { get; set; }
        public int DepartmentCode { get; set; }
        public int DistrictCode { get; set; }

        public int BlockCode { get; set; }
        public int UserId { get; set; }


    }


    public class UserAchievementSubCategoryViewModel
        {
        public long SubCategoryId { get; set; }
        public int SubCategoryCode { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public int CategoryCode { get; set; }
        public string Title { get; set; }
        public string TitleHindi { get; set; }
      
     

        }
    public class UserDivisionViewModel
    {
        public int DivisionCode { get; set; }
        public string DivisionTitle { get; set; }
        public string DivisionTitleHindi { get; set; }
        public string DivisionShortTitle { get; set; }
        public string DivisionShortTitleHindi { get; set; }
        public int UserId { get; set; }
    }
    public class UserDistrictViewModel
    {
        public int DistrictCode { get; set; }
        public string DistrictTitle { get; set; }
        public string DistrictTitleHindi { get; set; }
        public string DistrictShortTitle { get; set; }
        public string DistrictShortTitleHindi { get; set; }
        public int DivisionCode { get; set; }
        public string DivisionTitle { get; set; }
        public int UserId { get; set; }
    }

    public class UserTehsilViewModel
    {
        public int TehsilCode { get; set; }
        public string TehsilTitle { get; set; }
        public string TehsilTitleHindi { get; set; }
        public int DistrictCode { get; set; }
        public string DistrictTitle { get; set; }
        public int UserId { get; set; }
    }

    public class UserBlockViewModel
    {
        public int BlockCode { get; set; }
        public string BlockTitle { get; set; }
        public string BlockTitleHindi { get; set; }
        public int DistrictCode { get; set; }
        public string DistrictTitle { get; set; }
        public int UserId { get; set; }
    }

    public class LoginUserLogModel
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string SSOID { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
        public string IPAddress { get; set; }
        public string LoginLogOutStaus { get; set; }
        public Nullable<bool> IsActive { get; set; } = true;
        public Nullable<bool> IsDeleted { get; set; }=false;
    }

    public class UserForNotificationListModel
    {
        public string UserName { get; set; }
        public string SSOID { get; set; }
        public int UserId { get; set; }
        public string UserEmail { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> User_DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public Nullable<int> OfficeCode { get; set; }
        public string OfficeName { get; set; }
    }

    public class UserNotificationModel
    {
        public string Content { get; set; }
        public List<string> MobileNo { get; set; }
        public bool IsSelectAll { get; set; }
        public List<string> UnSelectedList { get; set; }
        public string MobileNumber { get; set; }
        public UserNotificationFilterModel FilterModel { get; set; }
    }

    public class UserNotificationFilterModel:IndexModel
    {
        public int? OfficeCode { get; set; }
        public int? DepartmentCode { get; set; }
    }

    public class UserDetailFilterModel : IndexModel
    {
        public string UserType { get; set; }
        public int DepartmentCode { get; set; }
      
    }

    public class UserPagePermissionByUserModel
    {
        public long UserPagePermissionId { get; set; }
        public int UserId { get; set; }
        public string ApplicationTitle { get; set; }
        public string PageTitle { get; set; }
        public bool AddPermission { get; set; }
        public bool EditPermission { get; set; }
        public bool DeletePermission { get; set; }
        public bool ViewPermission { get; set; }
    }

    public class UserTypeWhichHasApefificPermissionModel
    {
        public int UserTypeId { get; set; }
        public string UserTypeTitle { get; set; }
        public string UserType { get; set; }
    }

    public class UserWhichHasApefificPermissionModel
    {
        public int UserId { get; set; }
        public string UserType { get; set; }
        public string UserTypeTitle { get; set; }
        public string UserName { get; set; }
    }

    public class UserWhichHasDefaultPermissionModel
    {
        public int UserTypeId { get; set; }
        public string UserType { get; set; }
        public string UserTypeTitle { get; set; }
        public long PageCode { get; set; }
    }

    public class MobileAppLoginModel
    {
        public string SSOID { get; set; }
        public string Password { get; set; }
    }

}
