
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CMOWebApi.Models
{
    // You can add profile data for the user by adding more properties to your ApplicationUser class, please visit http://go.microsoft.com/fwlink/?LinkID=317594 to learn more.
    public class ApplicationUser : IdentityUser
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Avatar { get; set; }
        public bool? Deleted { get; set; }
        public async Task<ClaimsIdentity> GenerateUserIdentityAsync(UserManager<ApplicationUser> manager)
        {
            var userIdentity = await manager.CreateIdentityAsync(this, DefaultAuthenticationTypes.ApplicationCookie);
            if (this.FirstName != null)
            {
                userIdentity.AddClaim(new Claim(ClaimTypes.GivenName, this.FirstName));
                userIdentity.AddClaim(new Claim(ClaimTypes.Surname, this.LastName));
            }
            return userIdentity;
        }
    }

    public class ApplicationDbContext : IdentityDbContext<ApplicationUser>
    {
        public ApplicationDbContext()
            : base("DefaultConnection", throwIfV1Schema: false)
        {
        }
        public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblSetting> tblSetting { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblCity> tblCities { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblState> tblStates { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblCountry> tblCountries { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tbllookup> tbllookups { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tbllookuptype> tbllookuptypes { get; set; }
        public DbSet<CMOWebApi.Models.AutoGeneratedModels.Menu> Menus { get; set; }
        public DbSet<CMOWebApi.Models.AutoGeneratedModels.MenuType> MenuTypes { get; set; }
        public DbSet<CMOWebApi.Models.AutoGeneratedModels.CmsPage> CmsPages { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.ExceptionLogger> ExceptionLoggers { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblNew> tblNews { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblNewsPhoto> tblNewsPhotos { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblPermission> tblPermissions { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.LNK_ROLE_PERMISSION> LNK_ROLE_PERMISSION { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblRoleFunctionality> tblRoleFunctionality { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblUserTokenRef> tblUserToken { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblSystemFunctionality> tblSystemFunctionality { get; set; }
        
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblBlog> tblBlog { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblBlogCommentRef> tblBlogComment { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tblActivityLog> tblActivityLog { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.SmtpDetail> SmtpDetail { get; set; }

        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.GlobalMacro> GlobalMacro { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.EmailType> EmailType { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.EmailTemplate> EmailTemplate { get; set; }
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.AppointmentDiary> AppointmentDiary { get; set; }
        
        //Add More tables
        //public DbSet<CMOWebApi.Models.AutoGeneratedModels.tablename> CmsPages { get; set; }

        public static ApplicationDbContext Create()
        {
            return new ApplicationDbContext();
        }
    }
     
}
