using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
   [Table("CmsPage")]
    public partial class CmsPage
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Heading { get; set; }
        public string PageContent { get; set; }
        public bool IsActive { get; set; }
    }
}
