using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("EmailTemplates")]
    public partial class EmailTemplate
    {
        [Key]
        public int Id { get; set; }
        public int EmailTypeId { get; set; }
        public string Subject { get; set; }
        public string EmailContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }

        [ForeignKey("EmailTypeId")]
        public virtual EmailType EmailType { get; set; }
    }
}
