using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("EmailType")]
    public partial class EmailType
    {
        [Key]
        public int Id { get; set; }
        public string Type { get; set; }
        public string EmailTypeCode { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
