using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("ExceptionLogger")]
    public partial class ExceptionLogger
    {
        [Key]
        public long Id { get; set; }
        public Nullable<System.Guid> ExceptionId { get; set; }
        public string ExceptionMessage { get; set; }
        public string ExceptionType { get; set; }
        public string ExceptionSource { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> IsResolved { get; set; }
    }
}
