using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("GlobalMacros")]
    public partial class GlobalMacro
    {
        [Key]
        public int Id { get; set; }
        public string MacroName { get; set; }
        public string MacroCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
