
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNet.Identity.EntityFramework;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("LNK_ROLE_PERMISSION")]
    public class LNK_ROLE_PERMISSION
    {
        [Key]
        [Column(Order = 1)]
        public string Role_Id { get; set; }
        [Key]
        [Column("Permission_Id", Order = 2)]
        public int Permission_Id_Ref { get; set; }

        [ForeignKey("Permission_Id_Ref")]
        public virtual tblPermission tblPermission { get; set; }


        [ForeignKey("Role_Id")]
        public virtual IdentityRole AspNetRoles { get; set; }
    }
}
