using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("MenuType")]
    public partial class MenuType
    {
        public MenuType()
        {
            this.Menus = new HashSet<Menu>();
        }
        [Key]
        public byte Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }

        public virtual ICollection<Menu> Menus { get; set; }
    }
}

