using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("Menus")]
    public partial class Menu
    {
        [Key]
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<byte> MenuTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string Css { get; set; }
        public string Icon { get; set; }
        public string RoleId { get; set; }
        public bool IsDefault { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> OrderBy { get; set; }

        public virtual MenuType MenuType { get; set; }
    }

    public class MenuViewModel
    {
        public int MenuId { get; set; }
        public int MenuCode { get; set; }
        [Display(Name = "Menu Title")]
        [Required(ErrorMessage = "{0} is Required!")]
        public string MenuTitle { get; set; }
        [Display(Name = "Application")]
        [Required(ErrorMessage = "{0} is Required!")]
        public string ApplicationCode { get; set; }
        [Display(Name = "Default Url")]
        [Required(ErrorMessage = "{0} is Required!")]
        public string DefaultUrl { get; set; }
        [Display(Name = "Menu Icon Class")]
        [Required(ErrorMessage = "{0} is Required!")]
        public string MenuIconClass { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
    public class UserMenuViewModel
    {
        public string displayName { get; set; }
        //disabled?: boolean;
        public string iconName { get; set; }
        public string route { get; set; }
        public List<UserMenuViewModel> children { get; set; }
    }
}
