using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("SmtpDetails")]
    public partial class SmtpDetail
    {
        [Key]
        public int Id { get; set; }
        public string SmtpUser { get; set; }
        public string SmtpPassword { get; set; }
        public string SmtpPort { get; set; }
        public int EnableSsl { get; set; }
        public string SmtpHost { get; set; }
    }
}
