using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblActivityLog")]
    public partial class tblActivityLog
    {
        [Key]
        public long Id { get; set; }
        public string UserID { get; set; }
        public string AccessArea { get; set; }
        public string AccessPath { get; set; }
        public string IP { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> DateAndTime { get; set; }
        public Nullable<bool> IsSuccess { get; set; }
        public Nullable<System.Guid> ExceptionId { get; set; }
    }
}
