using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblBlog")]
    public partial class tblBlog
    {
        [Key]
        public long Id { get; set; }
        public string Title { get; set; }
        public System.DateTime BlogDate { get; set; }
        public string AuthorName { get; set; }
        public string ShortDesc { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string metaTag { get; set; }
        public string pageTitle { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
