using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblCity")]
    public partial class tblCity
    {
        [Key]
        public int Id { get; set; }
        public string CityName { get; set; }
        public int StateId { get; set; }
        public bool IsActive { get; set; }

        [ForeignKey("StateId")]
        public virtual tblState tblState { get; set; }
    }
}
