using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tbllookup")]
    public partial class tbllookup
    {
        [Key]
        public long Id { get; set; }
        
        public string lookup { get; set; }
        public string desc { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> lookupTypeId { get; set; }
        public Nullable<int> sortOrder { get; set; }

        [ForeignKey("lookupTypeId")]
        public virtual tbllookuptype tbllookuptype { get; set; }
    }
}
