using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tbllookuptype")]
    public partial class tbllookuptype
    {
        [Key]
        public int Id { get; set; }
        public string lookupType { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
