using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblNewsPhoto")]
    public partial class tblNewsPhoto
    {
        [Key]
        public long Id { get; set; }
        public Nullable<long> NewsId { get; set; }
        public string FileName { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public Nullable<bool> IsPhoto { get; set; }
        public Nullable<bool> isActive { get; set; }

        [ForeignKey("NewsId")]
        public virtual tblNew tblNew { get; set; }
    }
}
