using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblNew")]
    public partial class tblNew
    {
        [Key]
        public long Id { get; set; }
        public string Title { get; set; }
        public System.DateTime NewsDate { get; set; }
        public string AuthorName { get; set; }
        public string ShortDesc { get; set; }
        public Nullable<long> SourceId { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public Nullable<long> ParentNewsId { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string metaTag { get; set; }
        public string pageTitle { get; set; }
        public Nullable<bool> isActive { get; set; }

        [ForeignKey("SourceId")]
        public virtual tbllookup tbllookup { get; set; }
        [ForeignKey("CategoryId")]
        public virtual tbllookup tbllookup1 { get; set; }
        [ForeignKey("ParentNewsId")]
        public virtual tblNew tblNew1 { get; set; }
        
        public virtual ICollection<tblNew> tblNews1 { get; set; }
        public virtual ICollection<tblNewsPhoto> tblNewsPhotoes { get; set; }
    }
}
