using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("[tblPermissions]")]
    public partial class tblPermission
    {
        [Key]
        public int Permission_id { get; set; }
        public string PermissionDescription { get; set; }
    }
}
