using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblRoleFunctionality")]
    public partial class tblRoleFunctionality
    {
        [Key]
        public string RoleID { get; set; }
        public int SystemFunctionalityID { get; set; }
        public bool IsView { get; set; }
        public bool IsAdd { get; set; }
        public bool IsEdit { get; set; }
        public bool IsDelete { get; set; }
        public bool IsImport { get; set; }
        public bool IsExport { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte ActiveStatus { get; set; }

        [ForeignKey("SystemFunctionalityID")]
        public virtual tblSystemFunctionality tblSystemFunctionality { get; set; }
    }
}
