using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblSystemFunctionality")]
    public partial class tblSystemFunctionality
    {
        [Key]
        public int SystemFunctionalityID { get; set; }
        public string FunctionalityName { get; set; }
        public string FunctionalityCode { get; set; }
        public bool IsActive { get; set; }
        public int? ParentSystemFunctionalityID { get; set; }
        public string FunctionalityCommand { get; set; }
        public string FunctionalityPageURL { get; set; }
        public int FunctionalityOrderID { get; set; }
        public bool IsAddEnable { get; set; }
        public bool IsEditEnable { get; set; }
        public bool IsViewEnable { get; set; }
        public bool IsImportEnable { get; set; }
        public bool IsExportEnable { get; set; }
        public bool IsDeleteEnable { get; set; }
        public bool IsSetup { get; set; }
        public bool IsMenu { get; set; }
        public string AltText { get; set; }
        public string LastModifiedBy { get; set; }
        public DateTime LastModifiedDate { get; set; }
        public byte ActiveStatus { get; set; }
    }
}
