using CMOWebApi.Models.LoginModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Models.AutoGeneratedModels
{
    [Table("tblUserToken")]
    public partial class tblUserToken
    {
        [Key]
        public int TokenId { get; set; }
        public string UserId { get; set; }
        public string DeviceToken { get; set; }
        public int? DeviceType { get; set; }
        public DateTime? CreatedDate { get; set; }
        public bool? IsActive { get; set; }

    }

    [Table("tblUserToken")]
    public partial class tblUserTokenRef
    {
        [Key]
        public int TokenId { get; set; }
        [Column("UserId")]
        public string UserId_ref { get; set; }
        public string DeviceToken { get; set; }
        public int? DeviceType { get; set; }
        public System.DateTime? CreatedDate { get; set; }
        public bool? IsActive { get; set; }

        [ForeignKey("UserId_ref")]
        public virtual ApplicationUser AspNetUser { get; set; }
    }
}
