using CMOWebApi.Models.AdminModel;
using CMOWebApi.Models.AutoGeneratedModels;
using CMOWebApi.Services.ServiceHelper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CMOWebApi.Services.IServices
{
    public interface IMenuService
    {
        /// <summary>
        /// Get All Menu BY Permission
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        ServiceResponse<List<UserMenuViewModel>> GetAll(List<AssignedUserPagePermissionViewModel> model);
        /// <summary>
        /// Get All Menu BY User Id
        /// </summary>
        /// <param name="userId"></param>
        /// <returns></returns>
        ServiceResponse<List<UserMenuViewModel>> GetAllByUserId(int userId);
        Task<ServiceResponse<string>> Create(MenuViewModel model);
        Task<ServiceResponse<string>> Edit(MenuViewModel model);
        ServiceResponse<MenuViewModel> GetById(int id);
    }
}
