//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlllistingGPA
    {
        public Nullable<decimal> sno { get; set; }
        public string prj_type { get; set; }
        public string html_colorstatus { get; set; }
        public string cmpriority { get; set; }
        public string delays { get; set; }
        public string lstatus { get; set; }
        public string lstatus1 { get; set; }
        public string html_lstatus { get; set; }
        public string html_lstatus1 { get; set; }
        public string pdf { get; set; }
        public string intreq { get; set; }
        public string intlevel { get; set; }
        public string cmostatus { get; set; }
        public string dept_status { get; set; }
        public Nullable<System.DateTime> Dept_UpdateDate { get; set; }
        public Nullable<System.DateTime> CMO_UpdateDate { get; set; }
        public string CMO_Comments { get; set; }
        public string Dept_Comments { get; set; }
        public Nullable<decimal> ModuleID { get; set; }
        public string modulename { get; set; }
    }
}
