//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cm_budgetyear
    {
        public string Cancel { get; set; }
        public Nullable<decimal> Sourceid { get; set; }
        public string MapName { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Wkid { get; set; }
        public Nullable<decimal> App_level { get; set; }
        public Nullable<decimal> App_desc { get; set; }
        public Nullable<decimal> App_slevel { get; set; }
        public string CancelRemarks { get; set; }
        public string WFRoles { get; set; }
        public string budgetyear { get; set; }
        public Nullable<System.DateTime> budgetdate { get; set; }
        public Nullable<decimal> cm_budgetyearid { get; set; }
        public string active { get; set; }
        public string inactive { get; set; }
        public string currentyear { get; set; }
        public string currentgovyear { get; set; }
        public string finyear { get; set; }
        public int JankalyanId { get; set; }
    }
}
