//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_DEPARTMENT
    {
        public decimal cm_departmentid { get; set; }
        public string Cancel { get; set; }
        public Nullable<decimal> Sourceid { get; set; }
        public string MapName { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Modifiedon { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string Wkid { get; set; }
        public Nullable<decimal> App_level { get; set; }
        public Nullable<decimal> App_desc { get; set; }
        public Nullable<decimal> App_slevel { get; set; }
        public string CancelRemarks { get; set; }
        public string WFRoles { get; set; }
        public string deptname { get; set; }
        public string deptnameh { get; set; }
        public string inactive { get; set; }
        public string lmsmarkedto { get; set; }
        public string deptshort { get; set; }
        public Nullable<decimal> olddeptid { get; set; }
        public string lmsmarkedtoh { get; set; }
        public string deptshorth { get; set; }
        public string lmsonly { get; set; }
        public string ldeptname { get; set; }
        public string ldeptnameh { get; set; }
        public string adeptname { get; set; }
        public string deptgroup { get; set; }
        public Nullable<decimal> DistrictCD { get; set; }
        public Nullable<decimal> disporder { get; set; }
        public string ftmsfilename { get; set; }
        public string ftmsdeptflg { get; set; }
    }
}
