//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMISNEW_cm_pstatusdtl
    {
        public long ID { get; set; }
        public string status { get; set; }
        public string stdate { get; set; }
        public string endate { get; set; }
        public string colorcode { get; set; }
        public string openstatus { get; set; }
        public string modulename { get; set; }
        public Nullable<decimal> cm_pstatusdtlid { get; set; }
        public string modwise { get; set; }
        public string actwise { get; set; }
        public Nullable<decimal> cm_pstatushdrid { get; set; }
        public string colorstatus { get; set; }
        public string color { get; set; }
        public Nullable<decimal> cm_pstatusdtlrow { get; set; }
        public Nullable<int> ModuleID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> OLDModuleID { get; set; }
    }
}
