//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMISNew_Trans_CoreTemp
    {
        public int ID { get; set; }
        public Nullable<decimal> CMIS_ID { get; set; }
        public string Project_Code { get; set; }
        public Nullable<decimal> ModuleID { get; set; }
        public Nullable<System.DateTime> App_Date { get; set; }
        public string Financial_Year { get; set; }
        public Nullable<decimal> Nodal_Department { get; set; }
        public Nullable<bool> Send_to_Department { get; set; }
        public string Para_No { get; set; }
        public string Part_No { get; set; }
        public string Sub_Para_No { get; set; }
        public string File_Number { get; set; }
        public Nullable<decimal> CM_Reply_Description { get; set; }
        public Nullable<decimal> Announcement_Type { get; set; }
        public string Announcement_Description { get; set; }
        public string Announcement_Description_Gist { get; set; }
        public Nullable<bool> Is_related_to_Manifesto { get; set; }
        public Nullable<bool> Action_not_required { get; set; }
        public Nullable<System.DateTime> Sent_to_Dept_on { get; set; }
        public string Beneficiary_District { get; set; }
        public Nullable<decimal> Place_District { get; set; }
        public string Place_Village { get; set; }
        public string Place_Panchayat { get; set; }
        public Nullable<decimal> Place_Assembly_Constituency { get; set; }
        public Nullable<decimal> Place_Parliamentary_Constituency { get; set; }
        public Nullable<decimal> Place_of_Announcement { get; set; }
        public Nullable<decimal> Event_Type { get; set; }
        public Nullable<decimal> Meeting_ID { get; set; }
        public Nullable<decimal> Announcement_Term { get; set; }
        public Nullable<bool> Is_CM_Priority { get; set; }
        public Nullable<decimal> Sector_Manifesto { get; set; }
        public Nullable<decimal> Manifesto_AnnouncementID { get; set; }
        public Nullable<decimal> Action_Point_No { get; set; }
        public Nullable<int> Action_Plan_No { get; set; }
        public Nullable<decimal> Action_Plan_Period { get; set; }
        public string Beneficiary_Category { get; set; }
        public Nullable<decimal> Financial_Resource { get; set; }
        public Nullable<bool> Is_Construction { get; set; }
        public string Decision_No { get; set; }
        public Nullable<System.DateTime> Decision_Date { get; set; }
        public string Executing_Agency { get; set; }
        public Nullable<decimal> Delay_ReasonID { get; set; }
        public string Delay_Reason_Remark { get; set; }
        public string Area_Division { get; set; }
        public string Area_District { get; set; }
        public string Area_Panchayat_Samiti { get; set; }
        public string Area_Assembly_Constituency { get; set; }
        public string Area_Parliamentary_Constituency { get; set; }
        public Nullable<int> Area_NO_Of_Village { get; set; }
        public Nullable<int> Area_NO_Of_GramPanchayat { get; set; }
        public Nullable<bool> Area_AllRajasthan { get; set; }
        public Nullable<bool> IsActualbenefitedStart { get; set; }
        public Nullable<System.DateTime> Benefited_StartDate { get; set; }
        public Nullable<decimal> Dept_Status_ID { get; set; }
        public string Dept_Status { get; set; }
        public Nullable<decimal> CMO_Status_ID { get; set; }
        public string CMO_Status { get; set; }
        public Nullable<System.DateTime> Dept_UpdateDate { get; set; }
        public Nullable<System.DateTime> CMO_UpdateDate { get; set; }
        public string Dept_Comments { get; set; }
        public string CMO_Comments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CretaedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> Delete_Status { get; set; }
        public Nullable<System.DateTime> re_deadline { get; set; }
        public string deadline_remarks { get; set; }
        public string manifesto_sector { get; set; }
        public string cmanifesto_sector { get; set; }
        public string manifesto_desc { get; set; }
        public Nullable<decimal> d1920 { get; set; }
        public Nullable<decimal> d2021 { get; set; }
        public Nullable<decimal> fd1920 { get; set; }
        public Nullable<decimal> fd2021 { get; set; }
        public string pstategov { get; set; }
        public string pcentralgov { get; set; }
        public string pexternalagency { get; set; }
        public string premarks { get; set; }
        public string pm_level { get; set; }
        public string pendinglevel { get; set; }
        public string pm_problem { get; set; }
        public string Benefited_Remarks { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> Financial_Year_ID { get; set; }
        public string CMDMaster_MeetingId { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> AnnouncementDate { get; set; }
        public string place_grampanchayat { get; set; }
        public string place_adistrict { get; set; }
        public string place_assconstituency { get; set; }
        public string place_parconstituency { get; set; }
        public Nullable<System.DateTime> CabinateDecision_Date { get; set; }
        public string verified { get; set; }
        public string govtflag { get; set; }
        public Nullable<System.DateTime> prj_revcompdate { get; set; }
        public string prj_type { get; set; }
        public string prj_name { get; set; }
        public string modulename { get; set; }
    }
}
