//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CMISNEW_CM_MODULEMaster
    {
        public int ID { get; set; }
        public decimal cm_moduleid { get; set; }
        public string Cancel { get; set; }
        public string modulename { get; set; }
        public string ModuleNameHindi { get; set; }
        public string modulesname { get; set; }
        public string ImagePath { get; set; }
        public bool IsVisibleOnFrontHome { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
