//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOP_Master
    {
        public int ID { get; set; }
        public string sno { get; set; }
        public string officername { get; set; }
        public string officernameh { get; set; }
        public string officercategorycode { get; set; }
        public string officercategory { get; set; }
        public string employeeid { get; set; }
        public string departmentcode { get; set; }
        public string departmentname { get; set; }
        public string departmentnameh { get; set; }
        public string designationcode { get; set; }
        public string designation { get; set; }
        public string designationh { get; set; }
        public string charge { get; set; }
        public string chargeh { get; set; }
        public string mobileno { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
