//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Masters_Admin_Audit_Log
    {
        public int SrNo { get; set; }
        public string User_ID { get; set; }
        public string IPAddress { get; set; }
        public string Unit_ID { get; set; }
        public string Application_ID { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> Date_Time { get; set; }
        public string Script { get; set; }
        public string Selectec_Database { get; set; }
        public string P_Details { get; set; }
        public Nullable<int> Tran_Code { get; set; }
        public string Remark { get; set; }
        public string Attachment { get; set; }
        public string IsNotificationViewed { get; set; }
        public Nullable<System.DateTime> Notification_ViewDate { get; set; }
    }
}
