//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemoveDuplicate
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TotalFrom { get; set; }
        public Nullable<int> TotalTo { get; set; }
        public Nullable<int> FromDeptCode { get; set; }
        public Nullable<int> TODeptCode { get; set; }
        public string FromDept { get; set; }
        public string TODept { get; set; }
    }
}
