//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_NotificationLookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblADV_NotificationLookup()
        {
            this.tblADV_RedesignPlatformUserLookup = new HashSet<tblADV_RedesignPlatformUserLookup>();
        }
    
        public long Id { get; set; }
        public Nullable<long> AdvertisementCode { get; set; }
        public Nullable<long> NotifiedUseDptCode { get; set; }
        public Nullable<bool> IsUploaded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblADV_RedesignPlatformUserLookup> tblADV_RedesignPlatformUserLookup { get; set; }
    }
}
