//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_RedesignPlatformUserLookup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblADV_RedesignPlatformUserLookup()
        {
            this.tblADV_RedesignRequestByPlatformUserLookup = new HashSet<tblADV_RedesignRequestByPlatformUserLookup>();
        }
    
        public long Id { get; set; }
        public Nullable<long> NotificationLookupId { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string Remaks { get; set; }
    
        public virtual tblADV_NotificationLookup tblADV_NotificationLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblADV_RedesignRequestByPlatformUserLookup> tblADV_RedesignRequestByPlatformUserLookup { get; set; }
    }
}
