//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAC_PC_DistrictLookup
    {
        public long AC_PC_DistLookupId { get; set; }
        public int AC_Code { get; set; }
        public int PC_Code { get; set; }
        public int DistrictCode { get; set; }
    }
}
