//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_AchievementBenificiaryMapping
    {
        public long Id { get; set; }
        public Nullable<int> AchievementsId { get; set; }
        public Nullable<int> BenificiaryId { get; set; }
    
        public virtual tblADV_Achievements tblADV_Achievements { get; set; }
    }
}
