//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_RedesignRequestByPlatformUserLookup
    {
        public long Id { get; set; }
        public Nullable<long> RedesignPlatformUserLookupId { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string RequestUrl { get; set; }
    
        public virtual tblADV_RedesignPlatformUserLookup tblADV_RedesignPlatformUserLookup { get; set; }
    }
}
