//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_AchievementCategoryDistrictDepartmentMappingLookUp
    {
        public long Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
    
        public virtual tblADV_AchievementCategoryMaster tblADV_AchievementCategoryMaster { get; set; }
    }
}
