//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdmDepartmentMaster
    {
        public int AdmDepartmentId { get; set; }
        public int AdmDepartmentCode { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public string AdmDepartmentTitleHindi { get; set; }
        public string AdmDepartmentShortTitle { get; set; }
        public string AdmDepartmentShortTitleHindi { get; set; }
        public bool AdmDepartmentIsActive { get; set; }
        public bool AdmDepartmentIsDeleted { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<decimal> CMIS_OLDID { get; set; }
    }
}
