//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblApplicationMaster
    {
        public int ApplicationId { get; set; }
        public string ApplicationCode { get; set; }
        public string ApplicationTitle { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string appIcon { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string DisplayTitle { get; set; }
    }
}
