//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_NotificationMaster
    {
        public long Id { get; set; }
        public long Code { get; set; }
        public Nullable<long> Type { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public Nullable<long> MappingCode { get; set; }
        public Nullable<long> ParentCode { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string PortalURL { get; set; }
        public Nullable<decimal> NotificationPeriod { get; set; }
        public Nullable<System.DateTime> LastNotifed { get; set; }
        public string AttachmentPath { get; set; }
        public Nullable<int> IsPullOrPushCode { get; set; }
        public string PullUserId { get; set; }
        public string PullPassword { get; set; }
        public string PushURL { get; set; }
        public string PushUserId { get; set; }
        public string PushPassword { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string SSOId { get; set; }
    }
}
