//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_AchievementSubCategoryMaster
    {
        public long SubCategoryId { get; set; }
        public int SubCategoryCode { get; set; }
        public int CategoryCode { get; set; }
        public string Title { get; set; }
        public string TitleHindi { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> DepartmentCod { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<bool> IsApplicableToAllDPT { get; set; }
        public Nullable<int> KPICategoryCode { get; set; }
    
        public virtual tblADV_AchievementCategoryMaster tblADV_AchievementCategoryMaster { get; set; }
    }
}
