//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAchievement_ConnectWithCMIS_Parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAchievement_ConnectWithCMIS_Parameter()
        {
            this.tblAchievement_ConnectWithCMIS_Result = new HashSet<tblAchievement_ConnectWithCMIS_Result>();
        }
    
        public long Id { get; set; }
        public int AchievementId { get; set; }
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string YearValue { get; set; }
        public string YearText { get; set; }
    
        public virtual tblADV_Achievements tblADV_Achievements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAchievement_ConnectWithCMIS_Result> tblAchievement_ConnectWithCMIS_Result { get; set; }
    }
}
