//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblADV_AdvertisementMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblADV_AdvertisementMaster()
        {
            this.tblADV_AdminDepartmentLookup = new HashSet<tblADV_AdminDepartmentLookup>();
            this.tblADV_BeneficiaryCategoryLookup = new HashSet<tblADV_BeneficiaryCategoryLookup>();
            this.tblADV_DistrictLookup = new HashSet<tblADV_DistrictLookup>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public string SubjectEng { get; set; }
        public string SubjectHin { get; set; }
        public Nullable<System.DateTime> AdvDate { get; set; }
        public string DocumentUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<long> Code { get; set; }
        public string PdfUrl { get; set; }
        public Nullable<bool> IsLock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblADV_AdminDepartmentLookup> tblADV_AdminDepartmentLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblADV_BeneficiaryCategoryLookup> tblADV_BeneficiaryCategoryLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblADV_DistrictLookup> tblADV_DistrictLookup { get; set; }
    }
}
