//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCOMPS_ActionLookUp
    {
        public long Id { get; set; }
        public long ComplaintEntryId { get; set; }
        public string AttachmentURL { get; set; }
        public string Comment { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual tblCOMPS_ComplaintEntry tblCOMPS_ComplaintEntry { get; set; }
        public virtual tblCOMPS_StatusMaster tblCOMPS_StatusMaster { get; set; }
    }
}
