//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCMO_ImportantDecisionAttachments
    {
        public long Id { get; set; }
        public int AchievementId { get; set; }
        public string Path { get; set; }
        public string AttachmentsName { get; set; }
        public string Description { get; set; }
    
        public virtual tblCMO_ImportantDecision tblCMO_ImportantDecision { get; set; }
    }
}
