//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCPT_ComparativeParameterBenificiaryMapping
    {
        public long Id { get; set; }
        public Nullable<long> ComparativeParameterId { get; set; }
        public Nullable<int> BenificiaryId { get; set; }
    
        public virtual tblCPT_ComparativeParameterMaster tblCPT_ComparativeParameterMaster { get; set; }
    }
}
