//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCOMPS_ComplaintEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCOMPS_ComplaintEntry()
        {
            this.tblCOMPS_AttachmentsLookUp = new HashSet<tblCOMPS_AttachmentsLookUp>();
            this.tblCOMPS_ActionLookUp = new HashSet<tblCOMPS_ActionLookUp>();
        }
    
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> EntryTypeId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string ScreenURL { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<long> PageCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCOMPS_AttachmentsLookUp> tblCOMPS_AttachmentsLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCOMPS_ActionLookUp> tblCOMPS_ActionLookUp { get; set; }
        public virtual tblCOMPS_EntryTypeMaster tblCOMPS_EntryTypeMaster { get; set; }
        public virtual tblCOMPS_ModuleMaster tblCOMPS_ModuleMaster { get; set; }
        public virtual tblCOMPS_PriorityMaster tblCOMPS_PriorityMaster { get; set; }
        public virtual tblCOMPS_StatusMaster tblCOMPS_StatusMaster { get; set; }
    }
}
