//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCPT_ComparativeParameterTargetParameterMapping
    {
        public long Id { get; set; }
        public Nullable<int> ComparativeParameterTargetId { get; set; }
        public Nullable<long> ParameterCode { get; set; }
        public string PhysicalValue { get; set; }
        public string FinancialValue { get; set; }
    
        public virtual tblCPT_ComparativeParameterTarget tblCPT_ComparativeParameterTarget { get; set; }
    }
}
