//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiranjeeviVisitorCount
    {
        public long Id { get; set; }
        public long VisitorCount { get; set; }
        public System.DateTime VisitorDate { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
