//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryMaster
    {
        public int CategoryId { get; set; }
        public int CategoryCode { get; set; }
        public string Category { get; set; }
        public string CategoryHindi { get; set; }
        public bool CategoryIsActive { get; set; }
        public bool CategoryIsDeleted { get; set; }
    }
}
