//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCOMPS_AttachmentsLookUp
    {
        public long Id { get; set; }
        public long ComplaintEntryId { get; set; }
        public string Path { get; set; }
    
        public virtual tblCOMPS_ComplaintEntry tblCOMPS_ComplaintEntry { get; set; }
    }
}
