//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCPT_DepartmentalProgressWebService
    {
        public int Id { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> YearCode { get; set; }
        public Nullable<int> MonthCode { get; set; }
        public Nullable<long> ParameterCode { get; set; }
        public string PhysicalValue { get; set; }
        public string FinancialValue { get; set; }
        public Nullable<int> PhysicalTargetValue { get; set; }
        public Nullable<int> FinancialTargetValue { get; set; }
        public Nullable<int> PendingValue { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
