//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCPT_CurrentGovtEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCPT_CurrentGovtEntry()
        {
            this.tblCPT_CurrentGovtEntryParameterMapping = new HashSet<tblCPT_CurrentGovtEntryParameterMapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> YearCode { get; set; }
        public Nullable<long> MonthCode { get; set; }
        public Nullable<int> KPICategoryCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<long> ParameterCategoryCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCPT_CurrentGovtEntryParameterMapping> tblCPT_CurrentGovtEntryParameterMapping { get; set; }
    }
}
