//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDynamicReport
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Query { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
    }
}
