//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDept_MenuClassificationMappingLookUp
    {
        public long Id { get; set; }
        public Nullable<int> MenuClassificationId { get; set; }
        public Nullable<long> ClassificationTypeCode { get; set; }
    
        public virtual tblDept_MenuClassification tblDept_MenuClassification { get; set; }
    }
}
