//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDept_SectionMaster
    {
        public long Id { get; set; }
        public long Code { get; set; }
        public string ComponentName { get; set; }
        public string SelectorName { get; set; }
        public string ShortDescription { get; set; }
        public bool IsActive { get; set; }
        public bool Isdeleted { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DefaultOrder { get; set; }
        public string NameEnglish { get; set; }
        public string NameHindi { get; set; }
    }
}
