//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDepartmentGroup
    {
        public int DepartmentGroupID { get; set; }
        public int DepartmentGroupCode { get; set; }
        public string DepartmentGroupTitle { get; set; }
        public string DepartmentGroupTitleHindi { get; set; }
        public bool DepartmentGroupIsActive { get; set; }
        public bool DepartmentGroupIsDeleted { get; set; }
    }
}
