//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PROJ_ProjectMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_PROJ_ProjectMaster()
        {
            this.tblJAN_PROJ_ProjectBudget_Parameter = new HashSet<tblJAN_PROJ_ProjectBudget_Parameter>();
            this.tblJAN_PROJ_ProjectMasterProjectsMapping = new HashSet<tblJAN_PROJ_ProjectMasterProjectsMapping>();
            this.tblJAN_PROJ_UpdateProgressMapping = new HashSet<tblJAN_PROJ_UpdateProgressMapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string ProjectSchemeName { get; set; }
        public long YearOfInitiationCode { get; set; }
        public long ProjectStatusCode { get; set; }
        public long ProjectSchemeProgramCode { get; set; }
        public int NodalDepartmentCode { get; set; }
        public long DevelopmentSectorCode { get; set; }
        public int ProjectCategoryCode { get; set; }
        public Nullable<int> ProjectSubCategoryCode { get; set; }
        public Nullable<bool> IsCMPriority { get; set; }
        public string ProjectSchemeDescription { get; set; }
        public string ProjectSchemeObjective { get; set; }
        public Nullable<bool> IsBeingInAuguratedByHCM { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string LabelName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> SubSubCategoryCode { get; set; }
        public Nullable<int> ProjectSchemeCode { get; set; }
        public Nullable<bool> IsCostCalculated { get; set; }
        public Nullable<bool> IsShilanyas { get; set; }
        public Nullable<System.DateTime> ShilanyasDate { get; set; }
        public Nullable<int> PerformedByMLACode { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectBudget_Parameter> tblJAN_PROJ_ProjectBudget_Parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectMasterProjectsMapping> tblJAN_PROJ_ProjectMasterProjectsMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_UpdateProgressMapping> tblJAN_PROJ_UpdateProgressMapping { get; set; }
    }
}
