//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_News_NewspaperCoverageTypes
    {
        public long Id { get; set; }
        public Nullable<long> NewsProgressId { get; set; }
        public Nullable<long> CoverageTypeCode { get; set; }
    
        public virtual tblJAN_News_NewspaperProgressMapping tblJAN_News_NewspaperProgressMapping { get; set; }
    }
}
