//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_TenderMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_TenderMaster()
        {
            this.tblJAN_TenderMapping = new HashSet<tblJAN_TenderMapping>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string RONo { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string NITNo { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string NITPurpose { get; set; }
        public Nullable<System.DateTime> FormIssuingDate { get; set; }
        public Nullable<System.DateTime> FormSubmissionDate { get; set; }
        public Nullable<System.DateTime> TenderOpeningDate { get; set; }
        public string SoftCopyURL { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_TenderMapping> tblJAN_TenderMapping { get; set; }
    }
}
