//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PROJ_ProjectBudget_Parameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_PROJ_ProjectBudget_Parameter()
        {
            this.tblJAN_PROJ_ProjectBudget_Result = new HashSet<tblJAN_PROJ_ProjectBudget_Result>();
        }
    
        public long Id { get; set; }
        public int ProjectMasterId { get; set; }
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string YearValue { get; set; }
        public string YearText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectBudget_Result> tblJAN_PROJ_ProjectBudget_Result { get; set; }
        public virtual tblJAN_PROJ_ProjectMaster tblJAN_PROJ_ProjectMaster { get; set; }
    }
}
