//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_News_NewspaperProgressMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_News_NewspaperProgressMapping()
        {
            this.tblJAN_News_NewspaperCoverageTypes = new HashSet<tblJAN_News_NewspaperCoverageTypes>();
            this.tblJAN_News_NewspaperProgressAttachments = new HashSet<tblJAN_News_NewspaperProgressAttachments>();
        }
    
        public long Id { get; set; }
        public Nullable<long> NewspaperTransId { get; set; }
        public string NewsHeadline { get; set; }
        public Nullable<long> PublicationTypeCode { get; set; }
        public string URL { get; set; }
        public string Caption { get; set; }
        public Nullable<int> NewspaperCode { get; set; }
        public Nullable<long> EditionCode { get; set; }
        public Nullable<long> PageNumberCode { get; set; }
        public string PDF { get; set; }
        public Nullable<long> NewsTypeCode { get; set; }
        public Nullable<int> ClassificationCode { get; set; }
        public string KeyPoint { get; set; }
        public string ActionRequiredIfAny { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsVisibleToPublic { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string NewsContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_News_NewspaperCoverageTypes> tblJAN_News_NewspaperCoverageTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_News_NewspaperProgressAttachments> tblJAN_News_NewspaperProgressAttachments { get; set; }
        public virtual tblJAN_News_NewspaperTransaction tblJAN_News_NewspaperTransaction { get; set; }
    }
}
