//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PROJ_UpdateProgressMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_PROJ_UpdateProgressMapping()
        {
            this.tblJAN_PROJ_UpdateProgressAttachmentMapping = new HashSet<tblJAN_PROJ_UpdateProgressAttachmentMapping>();
        }
    
        public long Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> MileStoneCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string PDF { get; set; }
        public Nullable<long> StatusCode { get; set; }
        public string MilestoneLabel { get; set; }
    
        public virtual tblJAN_PROJ_ProjectMaster tblJAN_PROJ_ProjectMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_UpdateProgressAttachmentMapping> tblJAN_PROJ_UpdateProgressAttachmentMapping { get; set; }
    }
}
