//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PressRelease_DIPR_With_Attachment
    {
        public decimal Id { get; set; }
        public string NEWS_ISACTIVE { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string DOCUMENT_FILE { get; set; }
        public string HEADING_IMAGE { get; set; }
        public string Description { get; set; }
        public string GeneralDescription { get; set; }
        public string NEWS_TYPE { get; set; }
        public string RELEASE_TYPE { get; set; }
        public Nullable<System.DateTime> SUBMIT_DATE { get; set; }
        public string SUPPORTING_IMAGE { get; set; }
        public string VIDEO { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<decimal> DISTRICT_ID { get; set; }
        public string VIP_ID { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsSpecialPressRelease { get; set; }
        public Nullable<long> PressReleaseLevelCode { get; set; }
        public Nullable<System.DateTime> PressreleaseDate { get; set; }
        public Nullable<bool> IsOldRecord { get; set; }
        public Nullable<long> DisplayOrder { get; set; }
        public string PressReleaseTime { get; set; }
        public string DistrictName { get; set; }
        public string VIPPErsonName { get; set; }
        public Nullable<int> DepartmentCode1 { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public Nullable<int> SubCategoryCode { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string URL { get; set; }
        public string PDFUrl { get; set; }
        public string ImageUrl { get; set; }
        public string HomePageImageUrl { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> Code { get; set; }
    }
}
