//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PressRelease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_PressRelease()
        {
            this.tblJAN_PressReleaseAttachment_103224 = new HashSet<tblJAN_PressReleaseAttachment_103224>();
            this.tblJAN_PressReleaseAttachment_1032241 = new HashSet<tblJAN_PressReleaseAttachment_103224>();
            this.tblJAN_PressReleaseVIPCategoryMapping = new HashSet<tblJAN_PressReleaseVIPCategoryMapping>();
            this.tblJAN_PressReleaseVIPPersionMapping = new HashSet<tblJAN_PressReleaseVIPPersionMapping>();
            this.tblJAN_PressReleaseDistrictMappingLookUp = new HashSet<tblJAN_PressReleaseDistrictMappingLookUp>();
            this.tblJAN_PressReleaseDepartmentMappingLookUp = new HashSet<tblJAN_PressReleaseDepartmentMappingLookUp>();
            this.tblJAN_PressReleaseImageAttachment_3424 = new HashSet<tblJAN_PressReleaseImageAttachment_3424>();
            this.tblJAN_PressReleaseImageAttachment = new HashSet<tblJAN_PressReleaseImageAttachment>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public Nullable<int> SubCategoryCode { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string GeneralDescription { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<long> DisplayOrder { get; set; }
        public string PDFUrl { get; set; }
        public string ImageUrl { get; set; }
        public string HomePageImageUrl { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsSpecialPressRelease { get; set; }
        public Nullable<long> PressReleaseLevelCode { get; set; }
        public Nullable<System.DateTime> PressreleaseDate { get; set; }
        public Nullable<bool> IsOldRecord { get; set; }
        public string PressReleaseTime { get; set; }
        public Nullable<decimal> DIPR_Id { get; set; }
        public string DistrictName { get; set; }
        public string VIPPersonName { get; set; }
        public Nullable<long> LookupCategoryCode { get; set; }
        public string NameOfVIPPerson { get; set; }
        public string AmountinLakh { get; set; }
        public string NoOfInaugration { get; set; }
        public string NoOfLokarpan { get; set; }
        public string NoOfNewInitatives { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseAttachment_103224> tblJAN_PressReleaseAttachment_103224 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseAttachment_103224> tblJAN_PressReleaseAttachment_1032241 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseVIPCategoryMapping> tblJAN_PressReleaseVIPCategoryMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseVIPPersionMapping> tblJAN_PressReleaseVIPPersionMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseDistrictMappingLookUp> tblJAN_PressReleaseDistrictMappingLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseDepartmentMappingLookUp> tblJAN_PressReleaseDepartmentMappingLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseImageAttachment_3424> tblJAN_PressReleaseImageAttachment_3424 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PressReleaseImageAttachment> tblJAN_PressReleaseImageAttachment { get; set; }
    }
}
