//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_News_NewspaperChairpersonMapping
    {
        public long Id { get; set; }
        public Nullable<long> NewspaperTransId { get; set; }
        public Nullable<long> ChairpersonCode { get; set; }
    
        public virtual tblJAN_News_NewspaperTransaction tblJAN_News_NewspaperTransaction { get; set; }
    }
}
