//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_TenderMapping
    {
        public long Id { get; set; }
        public Nullable<int> TenderId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PDFUrl { get; set; }
    
        public virtual tblJAN_TenderMaster tblJAN_TenderMaster { get; set; }
    }
}
