//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PROJ_UpdateProgressAttachmentMapping
    {
        public long Id { get; set; }
        public Nullable<long> UpdateProgressId { get; set; }
        public string Path { get; set; }
    
        public virtual tblJAN_PROJ_UpdateProgressMapping tblJAN_PROJ_UpdateProgressMapping { get; set; }
    }
}
