//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PROJ_ProjectMaster_099916
    {
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string ProjectSchemeName { get; set; }
        public long YearOfInitiationCode { get; set; }
        public long ProjectStatusCode { get; set; }
        public long ProjectSchemeProgramCode { get; set; }
        public int NodalDepartmentCode { get; set; }
        public long DevelopmentSectorCode { get; set; }
        public int ProjectCategoryCode { get; set; }
        public Nullable<int> ProjectSubCategoryCode { get; set; }
        public Nullable<bool> IsCMPriority { get; set; }
        public string ProjectSchemeDescription { get; set; }
        public string ProjectSchemeObjective { get; set; }
        public Nullable<bool> IsBeingInAuguratedByHCM { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string LabelName { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> SubSubCategoryCode { get; set; }
        public Nullable<int> ProjectSchemeCode { get; set; }
        public Nullable<bool> IsCostCalculated { get; set; }
        public Nullable<bool> IsShilanyas { get; set; }
        public Nullable<System.DateTime> ShilanyasDate { get; set; }
        public Nullable<int> PerformedByMLACode { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
    }
}
