//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_News_NewspaperTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_News_NewspaperTransaction()
        {
            this.tblJAN_News_NewspaperChairpersonMapping = new HashSet<tblJAN_News_NewspaperChairpersonMapping>();
            this.tblJAN_News_NewspaperProgressMapping = new HashSet<tblJAN_News_NewspaperProgressMapping>();
            this.tblJAN_News_NewsTransactionNodalDepartmentMapping = new HashSet<tblJAN_News_NewsTransactionNodalDepartmentMapping>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public string Topic { get; set; }
        public Nullable<int> SubjectCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> SourceTypeCode { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> IsVisibleToPublic { get; set; }
        public string SearchKeyword { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_News_NewspaperChairpersonMapping> tblJAN_News_NewspaperChairpersonMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_News_NewspaperProgressMapping> tblJAN_News_NewspaperProgressMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_News_NewsTransactionNodalDepartmentMapping> tblJAN_News_NewsTransactionNodalDepartmentMapping { get; set; }
    }
}
