//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_CategoryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_CategoryMaster()
        {
            this.tblJAN_CategoryMasterDistrictDepartmentMappingLookUp = new HashSet<tblJAN_CategoryMasterDistrictDepartmentMappingLookUp>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string SubMenuNameHindi { get; set; }
        public string SubMenuNameEnglish { get; set; }
        public Nullable<int> MenuClassificationCode { get; set; }
        public Nullable<int> MenuClassificationPageTypeCode { get; set; }
        public Nullable<long> GeneralDepartmentDistrictMapping { get; set; }
        public Nullable<bool> IsPressRelease { get; set; }
        public Nullable<long> CommonCategoryCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_CategoryMasterDistrictDepartmentMappingLookUp> tblJAN_CategoryMasterDistrictDepartmentMappingLookUp { get; set; }
    }
}
