//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PROJ_ProjectMasterProjectsMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblJAN_PROJ_ProjectMasterProjectsMapping()
        {
            this.tblJAN_PROJ_ProjectMasterProjectsMappingBlock_PS_Mapping = new HashSet<tblJAN_PROJ_ProjectMasterProjectsMappingBlock_PS_Mapping>();
            this.tblJAN_PROJ_ProjectMasterProjectsMappingGramPanchayatMapping = new HashSet<tblJAN_PROJ_ProjectMasterProjectsMappingGramPanchayatMapping>();
            this.tblJAN_PROJ_ProjectMasterProjectsMappingVillageMapping = new HashSet<tblJAN_PROJ_ProjectMasterProjectsMappingVillageMapping>();
            this.tblJAN_PROJ_ProjectMasterProjectsMappingDistrict = new HashSet<tblJAN_PROJ_ProjectMasterProjectsMappingDistrict>();
            this.tblJAN_PROJ_ProjectMasterProjectsMappingAttachments = new HashSet<tblJAN_PROJ_ProjectMasterProjectsMappingAttachments>();
            this.tblJAN_PROJ_ProjectMasterProjectsMappingMLAMapping = new HashSet<tblJAN_PROJ_ProjectMasterProjectsMappingMLAMapping>();
        }
    
        public long Id { get; set; }
        public Nullable<int> ProjectMasterId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string LabelName { get; set; }
        public Nullable<long> UrbanOrRural { get; set; }
        public Nullable<int> MPConstituency { get; set; }
        public Nullable<int> MLAConstituency { get; set; }
        public string AreaCovered { get; set; }
        public Nullable<bool> IsPartofMLALAD { get; set; }
        public string PDFURL { get; set; }
        public Nullable<long> ProjectWorkCategory { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> WardNo { get; set; }
        public string BlockText { get; set; }
    
        public virtual tblJAN_PROJ_ProjectMaster tblJAN_PROJ_ProjectMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectMasterProjectsMappingBlock_PS_Mapping> tblJAN_PROJ_ProjectMasterProjectsMappingBlock_PS_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectMasterProjectsMappingGramPanchayatMapping> tblJAN_PROJ_ProjectMasterProjectsMappingGramPanchayatMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectMasterProjectsMappingVillageMapping> tblJAN_PROJ_ProjectMasterProjectsMappingVillageMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectMasterProjectsMappingDistrict> tblJAN_PROJ_ProjectMasterProjectsMappingDistrict { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectMasterProjectsMappingAttachments> tblJAN_PROJ_ProjectMasterProjectsMappingAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblJAN_PROJ_ProjectMasterProjectsMappingMLAMapping> tblJAN_PROJ_ProjectMasterProjectsMappingMLAMapping { get; set; }
    }
}
