//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_ChildPageMaster
    {
        public long Id { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<long> PageCode { get; set; }
        public Nullable<long> PageDescriptionCategory { get; set; }
        public string Description { get; set; }
        public string PDFURL { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> LookupTypeId { get; set; }
        public Nullable<long> SchemeTypeCode { get; set; }
        public Nullable<int> PageTypeCode { get; set; }
    }
}
