//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PressReleaseVIPPersionMapping
    {
        public long Id { get; set; }
        public Nullable<long> PressReleaseId { get; set; }
        public Nullable<long> VIPPersionCode { get; set; }
    
        public virtual tblJAN_PressRelease tblJAN_PressRelease { get; set; }
    }
}
