//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJAN_PROJ_ProjectMasterProjectsMappingBlock_PS_Mapping
    {
        public long Id { get; set; }
        public Nullable<long> ProjectsMappingId { get; set; }
        public Nullable<int> BlockCode { get; set; }
    
        public virtual tblJAN_PROJ_ProjectMasterProjectsMapping tblJAN_PROJ_ProjectMasterProjectsMapping { get; set; }
    }
}
