//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbllookup
    {
        public long Id { get; set; }
        public string lookup { get; set; }
        public string desc { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<int> lookupTypeId { get; set; }
        public Nullable<int> sortOrder { get; set; }
        public Nullable<bool> IsRef { get; set; }
        public string NameHindi { get; set; }
        public Nullable<System.DateTime> CreatedModifiedDate { get; set; }
        public Nullable<int> CreatedModifiedBy { get; set; }
    
        public virtual tbllookuptype tbllookuptype { get; set; }
    }
}
