//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoginUserActivityLog
    {
        public long Id { get; set; }
        public Nullable<int> ModuleName { get; set; }
        public Nullable<long> PageName { get; set; }
        public string PageType { get; set; }
        public string SystemIp { get; set; }
        public string SSOID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Url { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
    }
}
