//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLMS_UserPagePermission
    {
        public long UserPagePermissionId { get; set; }
        public int PageId { get; set; }
        public int UserId { get; set; }
        public Nullable<bool> PageAdd { get; set; }
        public Nullable<bool> PageEdit { get; set; }
        public Nullable<bool> PageDelete { get; set; }
        public Nullable<bool> PageView { get; set; }
    }
}
