//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLMS_UserBasicPermission
    {
        public int BasicPermissionID { get; set; }
        public string User_UserType { get; set; }
        public Nullable<int> PagePermission_PageID { get; set; }
        public bool BasicPermission_AddNew { get; set; }
        public bool BasicPermission_Edit { get; set; }
        public bool BasicPermission_Delete { get; set; }
        public bool BasicPermission_View { get; set; }
    }
}
