//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenuMaster
    {
        public int MenuId { get; set; }
        public int MenuCode { get; set; }
        public string MenuTitle { get; set; }
        public string ApplicationCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public string DefaultUrl { get; set; }
        public string MenuIconClass { get; set; }
    }
}
