//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMLAConstituancyMaster
    {
        public int MLAConstituancyId { get; set; }
        public int MLAConstituancyCode { get; set; }
        public string MLAConstituancyTitle { get; set; }
        public string MLAConstituancyTitleHindi { get; set; }
        public Nullable<int> MLAConstituancy_PConstituancyCode { get; set; }
        public Nullable<int> MLAConstituancy_CategoryCode { get; set; }
        public Nullable<int> MLAConstituancy_ACCode { get; set; }
        public Nullable<int> MLAConstituancy_DistrictCode { get; set; }
        public bool MLAConstituancyIsActive { get; set; }
        public bool MLAConstituancyIsDeleted { get; set; }
        public Nullable<int> user_cd { get; set; }
        public Nullable<int> state_cd { get; set; }
        public Nullable<int> div_cd { get; set; }
        public string MLAName { get; set; }
        public string MLAParty { get; set; }
    }
}
