//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblODR_OrderRelatedToResult
    {
        public long Id { get; set; }
        public long RelatedToParameterID { get; set; }
        public string Projecthdrid { get; set; }
        public string ModuleName { get; set; }
        public string Year { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string ParaNo { get; set; }
        public string FileNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> CMISNewTransCoreId { get; set; }
    
        public virtual tblODR_OrderRelatedToParameter tblODR_OrderRelatedToParameter { get; set; }
    }
}
