//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblODR_OrderAttachments
    {
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string Path { get; set; }
        public string AttachmentsName { get; set; }
        public string Description { get; set; }
        public bool IsAnnexure { get; set; }
    
        public virtual tblODR_OrderEntryMaster tblODR_OrderEntryMaster { get; set; }
    }
}
