//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblODR_BenificiarySchemeLookup
    {
        public long Id { get; set; }
        public long OrderID { get; set; }
        public Nullable<long> SchemeCode { get; set; }
    
        public virtual tblODR_OrderEntryMaster tblODR_OrderEntryMaster { get; set; }
    }
}
