//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderTypeMaster_103499
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<long> Code { get; set; }
        public string ShortName { get; set; }
        public Nullable<bool> IsSystemGenerated { get; set; }
        public string ReportOrderType { get; set; }
        public Nullable<bool> IsDateMandatory { get; set; }
        public Nullable<int> IsDocumentNoMandatory { get; set; }
        public string ImagePath { get; set; }
        public string SubMenuNameHindi { get; set; }
        public string SubMenuNameEnglish { get; set; }
        public Nullable<int> MenuClassificationCode { get; set; }
        public Nullable<int> MenuClassificationPageTypeCode { get; set; }
        public Nullable<long> GeneralDepartmentDistrictMapping { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<long> CommonCategoryCode { get; set; }
        public Nullable<bool> IsShowInJankalyan { get; set; }
    }
}
