//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblODR_OrderEntryMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblODR_OrderEntryMaster()
        {
            this.tblODR_BeneficiaryCategoryLookup = new HashSet<tblODR_BeneficiaryCategoryLookup>();
            this.tblODR_BenificiarySchemeLookup = new HashSet<tblODR_BenificiarySchemeLookup>();
            this.tblODR_CancellationLookup = new HashSet<tblODR_CancellationLookup>();
            this.tblODR_DepartmentEffectedLookup = new HashSet<tblODR_DepartmentEffectedLookup>();
            this.tblODR_DepartmentLookup = new HashSet<tblODR_DepartmentLookup>();
            this.tblODR_GNRT_CorrespondenceCopyReferenceLookup = new HashSet<tblODR_GNRT_CorrespondenceCopyReferenceLookup>();
            this.tblODR_OrderAttachments = new HashSet<tblODR_OrderAttachments>();
            this.tblODR_OrderRelatedToParameter = new HashSet<tblODR_OrderRelatedToParameter>();
            this.tblODR_OrderSectorLookup = new HashSet<tblODR_OrderSectorLookup>();
        }
    
        public long Id { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrderNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectForm { get; set; }
        public string ReferenceLink { get; set; }
        public Nullable<long> IssueBy { get; set; }
        public string IndividualBeneficiaryScheme { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsOldOrder { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string SearchCriteria { get; set; }
        public string FileNumber { get; set; }
        public Nullable<long> LinkToScheme { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public string Subject { get; set; }
        public string Reference { get; set; }
        public string Context { get; set; }
        public Nullable<long> AuthoritySignatureCode { get; set; }
        public Nullable<long> CCSignatureCode { get; set; }
        public string OrdGenrateRemarks { get; set; }
        public string AddressTo { get; set; }
        public Nullable<bool> IsHindi { get; set; }
        public Nullable<bool> IsSaveAsDraft { get; set; }
        public string Content { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string ESignedFinalUrl { get; set; }
        public string ESignedUrl1 { get; set; }
        public string ESignedUrl2 { get; set; }
        public string ESignedUrl3 { get; set; }
        public string ESignedUrl4 { get; set; }
        public string ESignedUrl5 { get; set; }
        public string UINumber { get; set; }
        public Nullable<long> CCCategoryCode { get; set; }
        public Nullable<bool> IsByOrderOfGovernor { get; set; }
        public string IsByOrderOfGovernortext { get; set; }
        public Nullable<int> SubTypeCode { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<bool> IsWithinSecretariat { get; set; }
        public string DispatchNumber { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public Nullable<int> OfficeCode { get; set; }
        public string AutoKeyWord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_BeneficiaryCategoryLookup> tblODR_BeneficiaryCategoryLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_BenificiarySchemeLookup> tblODR_BenificiarySchemeLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_CancellationLookup> tblODR_CancellationLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_DepartmentEffectedLookup> tblODR_DepartmentEffectedLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_DepartmentLookup> tblODR_DepartmentLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_GNRT_CorrespondenceCopyReferenceLookup> tblODR_GNRT_CorrespondenceCopyReferenceLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_OrderAttachments> tblODR_OrderAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_OrderRelatedToParameter> tblODR_OrderRelatedToParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblODR_OrderSectorLookup> tblODR_OrderSectorLookup { get; set; }
    }
}
