//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblODR_GNRT_CCCategoryLookup
    {
        public long Id { get; set; }
        public Nullable<long> CCCategoryCode { get; set; }
        public Nullable<long> DptReferenceCode { get; set; }
    
        public virtual tblODR_GNRT_CCCategoryMaster tblODR_GNRT_CCCategoryMaster { get; set; }
        public virtual tblODR_GNRT_DepartmentReference tblODR_GNRT_DepartmentReference { get; set; }
    }
}
