//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPConstituancyMaster
    {
        public int PConstituancyId { get; set; }
        public int PConstituancyCode { get; set; }
        public string PConstituancyTitle { get; set; }
        public string PConstituancyTitleHindi { get; set; }
        public bool PConstituancyIsActive { get; set; }
        public bool PConstituancyIsDeleted { get; set; }
        public Nullable<int> PConstituancy_PCNumber { get; set; }
        public string category_cd { get; set; }
        public Nullable<int> State_cd { get; set; }
        public Nullable<int> div_cd { get; set; }
        public Nullable<int> dist_cd { get; set; }
        public string RecId_text { get; set; }
    }
}
