//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPageUrlLookup
    {
        public long PageUrlId { get; set; }
        public long PageCode { get; set; }
        public string PageUrl { get; set; }
        public string PermissionType { get; set; }
    }
}
