//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferenceeMaster
    {
        public int ReferenceeId { get; set; }
        public int ReferenceeCode { get; set; }
        public string ReferenceePrefix { get; set; }
        public string ReferenceePrefixHindi { get; set; }
        public string ReferenceeName { get; set; }
        public string ReferenceeNameHindi { get; set; }
        public string ReferenceeGender { get; set; }
        public string ReferenceeOffName { get; set; }
        public string ReferenceeOffNameHindi { get; set; }
        public string ReferenceeOffAddress1 { get; set; }
        public string ReferenceeOffAddress2 { get; set; }
        public string ReferenceeOffAddress3 { get; set; }
        public string ReferenceeOffAddressHindi1 { get; set; }
        public string ReferenceeOffAddressHindi2 { get; set; }
        public string ReferenceeOffAddressHindi3 { get; set; }
        public string ReferenceeOffDistrict { get; set; }
        public string ReferenceeOffDistrictHindi { get; set; }
        public string ReferenceeOffTehsil { get; set; }
        public string ReferenceeOffState { get; set; }
        public string ReferenceeOffStateHindi { get; set; }
        public string ReferenceeOffPinCode { get; set; }
        public string ReferenceeOffPhone { get; set; }
        public string ReferenceeOffFax { get; set; }
        public string ReferenceeOffEMail { get; set; }
        public string ReferenceeResAddress1 { get; set; }
        public string ReferenceeResAddress2 { get; set; }
        public string ReferenceeResAddress3 { get; set; }
        public string ReferenceeResAddressHindi1 { get; set; }
        public string ReferenceeResAddressHindi2 { get; set; }
        public string ReferenceeResAddressHindi3 { get; set; }
        public string ReferenceeResDistrict { get; set; }
        public string ReferenceeResDistrictHindi { get; set; }
        public string ReferenceeResTehsil { get; set; }
        public string ReferenceeResState { get; set; }
        public string ReferenceeResStateHindi { get; set; }
        public string ReferenceeResPinCode { get; set; }
        public string ReferenceeResPhone { get; set; }
        public string ReferenceeResFax { get; set; }
        public string ReferenceeResEMail { get; set; }
        public string ReferenceeMailAddress1 { get; set; }
        public string ReferenceeMailAddress2 { get; set; }
        public string ReferenceeMailAddress3 { get; set; }
        public string ReferenceeMailAddressHindi1 { get; set; }
        public string ReferenceeMailAddressHindi2 { get; set; }
        public string ReferenceeMailAddressHindi3 { get; set; }
        public string ReferenceeMailDistrict { get; set; }
        public string ReferenceeMailDistrictHindi { get; set; }
        public string ReferenceeMailTehsil { get; set; }
        public string ReferenceeMailState { get; set; }
        public string ReferenceeMailStateHindi { get; set; }
        public string ReferenceeMailPinCode { get; set; }
        public string ReferenceeMobile1 { get; set; }
        public string ReferenceeMobile2 { get; set; }
        public string ReferenceePortfolio { get; set; }
        public string ReferenceePortfolioHindi { get; set; }
        public string ReferenceeWebAddress { get; set; }
        public string ReferenceeAStatus { get; set; }
        public string ReferenceeAddressBy { get; set; }
        public string ReferenceeAddressByHindi { get; set; }
        public Nullable<int> Referencee_CategoryCode { get; set; }
        public Nullable<int> Referencee_VIPCategoryCode { get; set; }
        public Nullable<int> Referencee_PConstituancyCode { get; set; }
        public Nullable<int> Referencee_MLAConstituancyCode { get; set; }
        public Nullable<int> Referencee_DistrictCode { get; set; }
        public Nullable<int> Referencee_PartyCode { get; set; }
        public Nullable<int> Referencee_ACCode { get; set; }
        public bool ReferenceeIsMinister { get; set; }
        public bool ReferenceeIsAll { get; set; }
        public bool ReferenceeIsActive { get; set; }
        public bool ReferenceeIsDeleted { get; set; }
        public Nullable<int> Referencee_VIPCategoryCode_old { get; set; }
    }
}
