//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSCM_EntryLookUp
    {
        public long Id { get; set; }
        public long schemeId { get; set; }
        public Nullable<long> AdminDepartmentCode { get; set; }
        public Nullable<long> NodelDepartmentCode { get; set; }
        public string NodelOfficerName { get; set; }
        public string MobileNo { get; set; }
        public string EmailId { get; set; }
        public string SsoId { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public Nullable<int> BlockCode { get; set; }
        public Nullable<long> TahsilCode { get; set; }
        public Nullable<int> Type { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Address { get; set; }
    
        public virtual tblSCM_SchemeMaster tblSCM_SchemeMaster { get; set; }
    }
}
