//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSCM_FAQs
    {
        public long Id { get; set; }
        public long SchemeID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string AttachmentUrl { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        public virtual tblSCM_SchemeMaster tblSCM_SchemeMaster { get; set; }
    }
}
