//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSCM_SchemeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSCM_SchemeMaster()
        {
            this.tblSCM_BeneficiaryCategoryLookUp = new HashSet<tblSCM_BeneficiaryCategoryLookUp>();
            this.tblSCM_CasteCategoryLookUp = new HashSet<tblSCM_CasteCategoryLookUp>();
            this.tblSCM_ConnectWithCMIS_Parameter = new HashSet<tblSCM_ConnectWithCMIS_Parameter>();
            this.tblSCM_DistrictLookUp = new HashSet<tblSCM_DistrictLookUp>();
            this.tblSCM_EligibilityCriteriaLookUp = new HashSet<tblSCM_EligibilityCriteriaLookUp>();
            this.tblSCM_EntryLookUp = new HashSet<tblSCM_EntryLookUp>();
            this.tblSCM_FAQs = new HashSet<tblSCM_FAQs>();
            this.tblSCM_GetBeneficiaryLookup = new HashSet<tblSCM_GetBeneficiaryLookup>();
            this.tblSCM_GroupDetailLookUp = new HashSet<tblSCM_GroupDetailLookUp>();
            this.tblSCM_HowToPayLookUp = new HashSet<tblSCM_HowToPayLookUp>();
            this.tblSCM_MobileAppLookup = new HashSet<tblSCM_MobileAppLookup>();
            this.tblSCM_ModeofApplicationLookup = new HashSet<tblSCM_ModeofApplicationLookup>();
            this.tblSCM_ModeOfDeliveryLookUp = new HashSet<tblSCM_ModeOfDeliveryLookUp>();
            this.tblSCM_ModeOfDisbursementLookUp = new HashSet<tblSCM_ModeOfDisbursementLookUp>();
            this.tblSCM_MonitoringParameterDataEntry = new HashSet<tblSCM_MonitoringParameterDataEntry>();
            this.tblSCM_MonitoringParameterDataEntryFieldValue = new HashSet<tblSCM_MonitoringParameterDataEntryFieldValue>();
            this.tblSCM_MonitoringParameterMapping = new HashSet<tblSCM_MonitoringParameterMapping>();
            this.tblSCM_OtherDocumentLookUp = new HashSet<tblSCM_OtherDocumentLookUp>();
            this.tblSCM_ProgramAreaLookUp = new HashSet<tblSCM_ProgramAreaLookUp>();
            this.tblSCM_RequiredDocumentLookUp = new HashSet<tblSCM_RequiredDocumentLookUp>();
            this.tblSCM_TypeLookUp = new HashSet<tblSCM_TypeLookUp>();
        }
    
        public long Id { get; set; }
        public string ShortNameHindi { get; set; }
        public string NameHindi { get; set; }
        public string ShortNameEnglish { get; set; }
        public string NameEnglish { get; set; }
        public string Description { get; set; }
        public Nullable<long> OwnedBy { get; set; }
        public Nullable<decimal> OwnedBySate { get; set; }
        public Nullable<decimal> OwnedByCenter { get; set; }
        public Nullable<long> IsListedRGDPSAct { get; set; }
        public Nullable<decimal> DeliveryTimeInDays { get; set; }
        public Nullable<long> DesignatedOfficerReceivingDetailCode { get; set; }
        public Nullable<long> FirstAppeallateCode { get; set; }
        public Nullable<long> SecondAppeallateCode { get; set; }
        public Nullable<long> ApplyForScheme { get; set; }
        public Nullable<decimal> TimeOfValidationInMonth { get; set; }
        public Nullable<long> ExpiredOn { get; set; }
        public Nullable<System.DateTime> ExpriedOnDate { get; set; }
        public Nullable<decimal> ExpriedDurationInMonth { get; set; }
        public Nullable<long> MadeOfAppling { get; set; }
        public Nullable<long> MadeOfApplingOnlineBoth { get; set; }
        public string DepartmentWebsiteUrl { get; set; }
        public Nullable<long> IsServiceFees { get; set; }
        public Nullable<long> HowToPayFeeCode { get; set; }
        public string HelplineNo { get; set; }
        public Nullable<long> DelivarebleCode { get; set; }
        public string deliveryPaymentDetail { get; set; }
        public Nullable<long> ModeOfDisbursmentCode { get; set; }
        public string ModeOfDisbursment { get; set; }
        public Nullable<long> PaymentDisbursmentFrequency { get; set; }
        public Nullable<long> PaymentDisbursmentFrequencyInstallments { get; set; }
        public string PaymentDisbursmentFrequencyTillAPeriod { get; set; }
        public string ItemDetails { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<decimal> ServiceFeeAmount { get; set; }
        public string Scheme_URL { get; set; }
        public string SearchKeyWordOfDetails { get; set; }
        public string SearchKeyWordOfExecution { get; set; }
        public string SearchKeyWordOfEligible { get; set; }
        public string SearchKeyWordOfHowToApply { get; set; }
        public string SearchKeyWordOfBeneficiaryGet { get; set; }
        public string SearchKeyWordOfOtherDocument { get; set; }
        public string Benificiarytext { get; set; }
        public string EligiblityText { get; set; }
        public string HowToApplyText { get; set; }
        public string WhatWillBeneficiaryGet { get; set; }
        public string StartDate { get; set; }
        public string Logo { get; set; }
        public Nullable<long> TypeCode { get; set; }
        public string Designation { get; set; }
        public string BannerImage { get; set; }
        public string WebsiteUrl { get; set; }
        public string MobileAppIcon { get; set; }
        public string MobileAppUrl { get; set; }
        public Nullable<bool> IsbeneficiaryText { get; set; }
        public Nullable<bool> IsEligibityText { get; set; }
        public Nullable<bool> IsHowToApply { get; set; }
        public Nullable<bool> IsWhatWillBeneficiaryGet { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<int> NodelDepartmentCode { get; set; }
        public Nullable<long> AdminDepartmentCode { get; set; }
        public Nullable<long> PriorityInList { get; set; }
        public Nullable<bool> IsSaveAsDraft { get; set; }
        public string SSOID { get; set; }
        public Nullable<long> SchemeType { get; set; }
        public Nullable<long> VisitorCount { get; set; }
        public Nullable<int> PageType { get; set; }
        public string BeneficiaryPdf { get; set; }
        public string ServiceFeePdf { get; set; }
        public string HowtoPayFeeRemarks { get; set; }
        public string URLofDataofBeneficiaryonJansoochnaPortal { get; set; }
        public Nullable<long> SchemeOrServiceCode { get; set; }
        public string ModeofApplicationText { get; set; }
        public string DocumentCertificateLicenseDocument { get; set; }
        public Nullable<int> NumberOfInstallments { get; set; }
        public string AutoKeyWord { get; set; }
        public Nullable<bool> IsFlagShipScheme { get; set; }
        public string FlagshipImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_BeneficiaryCategoryLookUp> tblSCM_BeneficiaryCategoryLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_CasteCategoryLookUp> tblSCM_CasteCategoryLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_ConnectWithCMIS_Parameter> tblSCM_ConnectWithCMIS_Parameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_DistrictLookUp> tblSCM_DistrictLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_EligibilityCriteriaLookUp> tblSCM_EligibilityCriteriaLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_EntryLookUp> tblSCM_EntryLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_FAQs> tblSCM_FAQs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_GetBeneficiaryLookup> tblSCM_GetBeneficiaryLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_GroupDetailLookUp> tblSCM_GroupDetailLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_HowToPayLookUp> tblSCM_HowToPayLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_MobileAppLookup> tblSCM_MobileAppLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_ModeofApplicationLookup> tblSCM_ModeofApplicationLookup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_ModeOfDeliveryLookUp> tblSCM_ModeOfDeliveryLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_ModeOfDisbursementLookUp> tblSCM_ModeOfDisbursementLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_MonitoringParameterDataEntry> tblSCM_MonitoringParameterDataEntry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_MonitoringParameterDataEntryFieldValue> tblSCM_MonitoringParameterDataEntryFieldValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_MonitoringParameterMapping> tblSCM_MonitoringParameterMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_OtherDocumentLookUp> tblSCM_OtherDocumentLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_ProgramAreaLookUp> tblSCM_ProgramAreaLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_RequiredDocumentLookUp> tblSCM_RequiredDocumentLookUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_TypeLookUp> tblSCM_TypeLookUp { get; set; }
    }
}
