//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSCM_MonitoringParameterMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSCM_MonitoringParameterMapping()
        {
            this.tblSCM_MonitoringParameterDataEntryFieldValue = new HashSet<tblSCM_MonitoringParameterDataEntryFieldValue>();
        }
    
        public long Id { get; set; }
        public Nullable<long> SchemeId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> MonitoringParamId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSCM_MonitoringParameterDataEntryFieldValue> tblSCM_MonitoringParameterDataEntryFieldValue { get; set; }
        public virtual tblSCM_MonitoringParameterMaster tblSCM_MonitoringParameterMaster { get; set; }
        public virtual tblSCM_SchemeMaster tblSCM_SchemeMaster { get; set; }
    }
}
