//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSCM_MonitoringParameterDataEntryFieldValue
    {
        public long Id { get; set; }
        public Nullable<long> DataEntryId { get; set; }
        public Nullable<long> SchemeId { get; set; }
        public Nullable<long> MappingId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string FieldValue { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual tblSCM_MonitoringParameterDataEntry tblSCM_MonitoringParameterDataEntry { get; set; }
        public virtual tblSCM_MonitoringParameterMapping tblSCM_MonitoringParameterMapping { get; set; }
        public virtual tblSCM_SchemeMaster tblSCM_SchemeMaster { get; set; }
    }
}
