//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceMaster
    {
        public int ServiceId { get; set; }
        public string PortalName { get; set; }
        public string WebserviceName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string ServerIP { get; set; }
        public string Frequency { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
    }
}
