//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStateMaster
    {
        public int StateId { get; set; }
        public int StateCode { get; set; }
        public string State { get; set; }
        public string StateShortTitle { get; set; }
        public string StateHindi { get; set; }
        public string StateShortTitleHindi { get; set; }
        public bool StateIsActive { get; set; }
        public bool StateIsDeleted { get; set; }
    }
}
