//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserRoleLookUp
    {
        public int UserRoleLookUpId { get; set; }
        public Nullable<int> UserRoleLookUp_UserId { get; set; }
        public Nullable<int> UserRoleLookUp_RoleId { get; set; }
    }
}
