//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserTypeRoleLookUp
    {
        public int UserTypeRoleLookUpId { get; set; }
        public Nullable<int> UserTypeRoleLookUp_UserTypeId { get; set; }
        public Nullable<int> UserTypeRoleLookUp_RoleId { get; set; }
    }
}
