//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserActivityLog
    {
        public long LogId { get; set; }
        public int UserId { get; set; }
        public string ApplicationCode { get; set; }
        public string PageUrl { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string Browser { get; set; }
        public string IPAddress { get; set; }
        public string ActionDetail { get; set; }
    }
}
