//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVCParticipant
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<long> VCCreateCode { get; set; }
        public Nullable<long> ParticipantCategoryCode { get; set; }
        public Nullable<long> ParticipantCode { get; set; }
        public string Name { get; set; }
        public string Designation { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public Nullable<long> LocationCode { get; set; }
        public string LocationTextBox { get; set; }
        public Nullable<long> ModeCode { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string MobileNo { get; set; }
        public string VCCreateName { get; set; }
        public string ParticipantCategoryName { get; set; }
        public string ParticipantName { get; set; }
        public string LocationName { get; set; }
        public string DistrictName { get; set; }
        public string ModeName { get; set; }
        public Nullable<bool> IsPresent { get; set; }
    }
}
