//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVCParticipantMaster
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<long> ParticipantCategoryId { get; set; }
        public string DesignationHindi { get; set; }
        public string Charge { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string NameHindi { get; set; }
        public string NameEnglish { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DesignationEnglish { get; set; }
        public string AdditionalCharge { get; set; }
        public string DistrictAssigned { get; set; }
        public string StateAssigned { get; set; }
        public string EmailID { get; set; }
        public string ContactNumber { get; set; }
        public string DistrictCode { get; set; }
        public string PCName { get; set; }
        public string ACName { get; set; }
        public string title { get; set; }
    }
}
