//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConfigurePermissionServiceassign
    {
        public long Id { get; set; }
        public Nullable<int> ConfigurePermissionId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<long> DisplayOrder { get; set; }
        public string Type { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserType { get; set; }
        public string DepartmentCode { get; set; }
    }
}
