//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ComparativeParameterTarget
    {
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> KPICategoryCode { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string DepartmentTitle { get; set; }
        public string KPICategoryName { get; set; }
        public string YearName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string modifiedbyName { get; set; }
    }
}
