//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CMISModuleData
    {
        public string Announcement_Description { get; set; }
        public int ID { get; set; }
        public Nullable<decimal> ModuleID { get; set; }
        public string modulename { get; set; }
        public string ModuleNameHindi { get; set; }
        public Nullable<decimal> DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public Nullable<int> DepartmentPriority { get; set; }
        public Nullable<int> JanDepartmentCode { get; set; }
        public Nullable<System.DateTime> App_Date { get; set; }
        public string CMDMaster_MeetingId { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string DecisionNo { get; set; }
        public Nullable<System.DateTime> AnnouncementDate { get; set; }
        public string File_Number { get; set; }
        public string Financial_Year { get; set; }
        public string ParaNumber { get; set; }
        public string place_village { get; set; }
        public string place_grampanchayat { get; set; }
        public string place_panchayat { get; set; }
        public string place_adistrict { get; set; }
        public string place_assconstituency { get; set; }
        public string place_parconstituency { get; set; }
        public Nullable<System.DateTime> CabinateDecision_Date { get; set; }
        public bool isActive { get; set; }
        public bool isDelete { get; set; }
        public string AllSearch { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public string AdmDepartmentTitleHindi { get; set; }
        public Nullable<int> AdminDepartmentCode { get; set; }
        public string Dept_Status { get; set; }
        public string CMO_Status { get; set; }
        public Nullable<System.DateTime> CMIS_UpdateDataDate { get; set; }
        public string Project_Code { get; set; }
        public string CMO_Comments { get; set; }
        public string Dept_Comments { get; set; }
        public Nullable<System.DateTime> CretaedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Benefited_StartDate { get; set; }
        public Nullable<bool> Send_to_Department { get; set; }
        public Nullable<System.DateTime> Sent_to_Dept_on { get; set; }
        public string Para_No { get; set; }
        public string Part_No { get; set; }
        public string Sub_Para_No { get; set; }
        public Nullable<bool> Action_not_required { get; set; }
        public Nullable<bool> Is_CM_Priority { get; set; }
        public Nullable<bool> IsActualbenefitedStart { get; set; }
        public Nullable<System.DateTime> Dept_UpdateDate { get; set; }
        public Nullable<System.DateTime> CMO_UpdateDate { get; set; }
        public Nullable<long> CMOOfficerCode { get; set; }
    }
}
