//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_COMPS_ComplaintEntry
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> EntryTypeId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> ModuleId { get; set; }
        public string ScreenURL { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string ApplicationCode { get; set; }
        public Nullable<long> PageCode { get; set; }
        public string ModuleName { get; set; }
        public string PriorityName { get; set; }
        public string StatusName { get; set; }
        public string EntryTypeName { get; set; }
        public string PageTitle { get; set; }
        public string ApplicationTitle { get; set; }
        public Nullable<bool> IsDevFilter { get; set; }
        public Nullable<bool> IsAdmFilter { get; set; }
        public Nullable<bool> IsUserFilter { get; set; }
        public string Attachments { get; set; }
        public string createdByName { get; set; }
        public string CreatedUserContact { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> ActionBy { get; set; }
    }
}
