//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_JAN_PROJ_ExstingMLAConstituencyDistrictDpt
    {
        public int MLAConstituencyId { get; set; }
        public Nullable<int> MLAConstituencyCode { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public int NodalDepartmentCode { get; set; }
        public Nullable<int> ProjectMasterId { get; set; }
        public long ProjectStatusCode { get; set; }
    }
}
