//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Jan_Front_ProjectsMappingForList
    {
        public long Id { get; set; }
        public Nullable<int> ProjectMasterId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Description { get; set; }
        public string MLAConstituencyName { get; set; }
        public string MLAConstituencyNameHindi { get; set; }
        public string MLADistrictTitle { get; set; }
        public string MLADistrictTitleHindi { get; set; }
    }
}
