//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Jan_Front_ProjectMasterProjectsMapping
    {
        public long Id { get; set; }
        public Nullable<int> ProjectMasterId { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string LabelName { get; set; }
        public Nullable<long> UrbanOrRural { get; set; }
        public Nullable<int> MPConstituency { get; set; }
        public string MLAConstituency { get; set; }
        public string AreaCovered { get; set; }
        public Nullable<bool> IsPartofMLALAD { get; set; }
        public string PDFURL { get; set; }
        public Nullable<long> ProjectWorkCategory { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> WardNo { get; set; }
        public string BlockText { get; set; }
        public string MLAConstituencyName { get; set; }
        public string MLAConstituencyNameHindi { get; set; }
        public string MLANameEng { get; set; }
        public string MLANameHindi { get; set; }
        public string MLADistrictCode { get; set; }
        public string MLADistrictTitle { get; set; }
        public string MLADistrictTitleHindi { get; set; }
        public string MPConstituencyName { get; set; }
        public string MPConstituencyNameHindi { get; set; }
        public string MPNameEng { get; set; }
        public string MPNameHindi { get; set; }
        public Nullable<int> MPDistrictCode { get; set; }
        public string MPDistrictTitle { get; set; }
        public string MPDistrictTitleHindi { get; set; }
        public string AreaName { get; set; }
        public string AreaNameHindi { get; set; }
        public string ProjectWorkCategoryName { get; set; }
        public string ProjectWorkCategoryNameHindi { get; set; }
    }
}
