//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Jan_Front_NewsPaperProgressDetail
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public string Topic { get; set; }
        public Nullable<int> SubjectCode { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<long> SourceTypeCode { get; set; }
        public string Summary { get; set; }
        public Nullable<bool> IsVisibleToPublic { get; set; }
        public string SearchKeyword { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string SubjectName { get; set; }
        public string SubjectNameHindi { get; set; }
        public string SourceTypeName { get; set; }
        public string SourceTypeNameHindi { get; set; }
        public string AdmDepartmentCodes { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public string AdmDepartmentTitleHindi { get; set; }
        public string DepartmentCodes { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public string VIPCategoryCodes { get; set; }
        public string VIPCategoryName { get; set; }
        public string VIPCategoryNameHindi { get; set; }
        public string VIPCode { get; set; }
        public string VIPName { get; set; }
        public string VIPNameHindi { get; set; }
        public long ProgressID { get; set; }
        public string NewsHeadline { get; set; }
        public Nullable<long> PublicationTypeCode { get; set; }
        public string PublicationTypeTitle { get; set; }
        public string PublicationTypeTitleHindi { get; set; }
        public Nullable<long> EditionCode { get; set; }
        public string EditionTitle { get; set; }
        public string EditionTitleHindi { get; set; }
        public Nullable<long> PageNumberCode { get; set; }
        public string PageNumberTitle { get; set; }
        public string PageNumberTitleHindi { get; set; }
        public Nullable<int> NewsPaperCode { get; set; }
        public string NewsPaperName { get; set; }
        public string NewsPaperNameHindi { get; set; }
        public string CoverageTypeCode { get; set; }
        public string CoverageTypeName { get; set; }
        public string CoverageTypeNameHindi { get; set; }
        public Nullable<System.DateTime> ProgressDate { get; set; }
        public bool ProgressIsVisibleToPublic { get; set; }
        public string url { get; set; }
        public string PDF { get; set; }
        public string NewsContent { get; set; }
        public string AllSearch { get; set; }
    }
}
