//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Jan_Front_ProjectMasterForListWithDptWebsite
    {
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string ProjectSchemeName { get; set; }
        public long YearOfInitiationCode { get; set; }
        public long ProjectStatusCode { get; set; }
        public int NodalDepartmentCode { get; set; }
        public long DevelopmentSectorCode { get; set; }
        public int ProjectCategoryCode { get; set; }
        public Nullable<int> ProjectSubCategoryCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> SubSubCategoryCode { get; set; }
        public Nullable<int> ProjectSchemeCode { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public int AdmDepartmentCode { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public string AdmDepartmentTitleHindi { get; set; }
        public string CategoryName { get; set; }
        public string CategoryNameHindi { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryNameHindi { get; set; }
        public string SubCategoryLabelName { get; set; }
        public string SectorName { get; set; }
        public string SectorNameHindi { get; set; }
        public string YearOfInitiationName { get; set; }
        public string ProjectSchemeProgramName { get; set; }
        public string ProjectSchemeProgramNameHindi { get; set; }
        public string MLAConstituencyName { get; set; }
        public string MLAConstituencyNameHindi { get; set; }
        public string MLAConstituencyDistrictName { get; set; }
        public string MLAConstituencyDistrictNameHindi { get; set; }
        public string ProgramSchemeName { get; set; }
        public Nullable<int> WorkTypeCode { get; set; }
        public string WorkTypeName { get; set; }
        public string WorkTypeNameHindi { get; set; }
        public string Description { get; set; }
        public string KeyWord { get; set; }
        public Nullable<long> ProjectMappingId { get; set; }
    }
}
