//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_JAN_DptWebsite_DepartmentDetail
    {
        public int DepartmentId { get; set; }
        public Nullable<int> DepartmentCode_old { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public string DepartmentShortTitle { get; set; }
        public string DepartmentShortTitleHindi { get; set; }
        public string DepartmentAddress { get; set; }
        public string DepartmentAddressHindi { get; set; }
        public Nullable<int> DepartmentSerialNo { get; set; }
        public Nullable<int> DepartmentPrintOrder { get; set; }
        public Nullable<int> Department_DistrictCode { get; set; }
        public Nullable<int> Department_AdmDepartmentCode_old { get; set; }
        public Nullable<int> Department_GroupCode_old { get; set; }
        public Nullable<int> Department_DepartmentGroupCode_old { get; set; }
        public string DepartmentEmail { get; set; }
        public string DepartmentMobile { get; set; }
        public Nullable<bool> DepartmentIsActive { get; set; }
        public Nullable<bool> DepartmentIsDeleted { get; set; }
        public string DEPTM_ID_TEXT { get; set; }
        public string DEPTM_SELECTION { get; set; }
        public string DEPTM_MANIFESTO { get; set; }
        public string DEPTM_MANIFESTO_SECTOR { get; set; }
        public Nullable<int> DEPTM_CATG_CD { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> Department_AdmDepartmentCode { get; set; }
        public Nullable<int> Department_GroupCode { get; set; }
        public Nullable<int> Department_DepartmentGroupCode { get; set; }
        public string officername { get; set; }
        public string officerdesignation { get; set; }
        public string officeremail { get; set; }
        public string officerofficermobile { get; set; }
        public string officerofficerphone { get; set; }
        public string staffname1 { get; set; }
        public string staff1designation { get; set; }
        public string staff1email { get; set; }
        public string staff1mobile { get; set; }
        public string staff1phone { get; set; }
        public string staffname2 { get; set; }
        public string staff2designation { get; set; }
        public string staff2email { get; set; }
        public string staff2mobile { get; set; }
        public string staff2phone { get; set; }
        public string CMISDeptID { get; set; }
        public string DepartmentNodalOfficer { get; set; }
        public string Mobileno1 { get; set; }
        public string Mobileno2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string WebsiteName { get; set; }
        public string NodalOfficerName { get; set; }
        public string NodalOfficerDesignation { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string SSOID { get; set; }
        public Nullable<int> DepartmentCategoryCode { get; set; }
        public string DisplayName { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string YoutubeURL { get; set; }
        public string InstagramURL { get; set; }
        public Nullable<long> DepartmentDistrictCode { get; set; }
        public Nullable<long> CMOOfficerCode { get; set; }
        public string LogoUrl { get; set; }
        public Nullable<int> DisplayOrderWithinAdminDepartment { get; set; }
        public string DepartmentPassword { get; set; }
        public Nullable<bool> IsWebsiteFromJankalyanPortal { get; set; }
        public Nullable<int> CabinetMinisterCode { get; set; }
        public Nullable<int> StateMinisterCode { get; set; }
        public string WebsiteImage { get; set; }
        public string StateMinisterPhoto { get; set; }
        public string CabinetMinisterPhoto { get; set; }
        public string WebsiteDynamicCategory { get; set; }
        public string WebsiteDynamictransaction { get; set; }
        public string StateMinisterNameEnglish { get; set; }
        public string StateMinisterNameHindi { get; set; }
        public string CabinetMinisterNameEnglish { get; set; }
        public string CabinetMinisterNameHindi { get; set; }
    }
}
