//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_JAN_EntryTypeMasterList
    {
        public Nullable<int> Code { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> JankalyanCategoryCode { get; set; }
    }
}
