//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ODR_GNRT_GenerateOrdeDetail
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public string OrderNo { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsSaveAsDraft { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string TypeName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string DepartmentTitle { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string ESignedFinalUrl { get; set; }
        public string ESignedUrl1 { get; set; }
        public string ESignedUrl2 { get; set; }
        public string ESignedUrl3 { get; set; }
        public string ESignedUrl4 { get; set; }
        public string ESignedUrl5 { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<bool> IsWithinSecretariat { get; set; }
    }
}
