//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PROJ_FRONT_ExstingMLAConstituencyDistricts
    {
        public int DistrictCode { get; set; }
        public string DistrictTitle { get; set; }
        public string DistrictTitleHindi { get; set; }
        public Nullable<int> MLAConstituencyCode { get; set; }
        public string MLAConstituencyName { get; set; }
        public string MLAConstituencyNameHindi { get; set; }
        public Nullable<int> ProjectMasterId { get; set; }
    }
}
