//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PROJ_FRONT_ExstingYearOfInitiation
    {
        public long YearOfInitiationCode { get; set; }
        public string YearOfInitiationName { get; set; }
        public string YearOfInitiationNameHindi { get; set; }
    }
}
