//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PROJ_FRONT_ExstingSubcategorys
    {
        public Nullable<int> ProjectSubCategoryCode { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryNameHindi { get; set; }
        public int ProjectCategoryCode { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
    }
}
