//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwADV_FrontGeneralEntry
    {
        public int Id { get; set; }
        public string Achievement { get; set; }
        public string AchievementHindi { get; set; }
        public Nullable<int> AchievementCategoryCode { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string Description { get; set; }
        public string DescriptionHindi { get; set; }
        public int Priority { get; set; }
        public string PdfFIleName { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> AchievementDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsVisible { get; set; }
        public Nullable<long> AchievementSubCategoryCode { get; set; }
        public string CMOComments { get; set; }
        public bool IsActive { get; set; }
        public string ImagePath { get; set; }
        public string AchievementCategory { get; set; }
        public string AchievementCategoryHindi { get; set; }
        public bool AchievementCategoryIsVisible { get; set; }
        public Nullable<bool> CategorydepVisible { get; set; }
        public string AchievementCategoryImagePath { get; set; }
        public string AchievementSubCategory { get; set; }
        public string AchievementSubCategoryHindi { get; set; }
        public string AchievementSubCategoryImagePath { get; set; }
        public string Department { get; set; }
        public string DepartmentHindi { get; set; }
        public Nullable<int> AdmDepartmentCode { get; set; }
        public string AdmDepartment { get; set; }
        public string AdmDepartmentHindi { get; set; }
        public Nullable<bool> IsVisibleToEndUser { get; set; }
        public string AllSearch { get; set; }
        public Nullable<long> CommonCategoryCode { get; set; }
    }
}
