//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwADV_AdvertisementList_Front
    {
        public long Id { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> SubCategory { get; set; }
        public string SubjectEng { get; set; }
        public string SubjectHin { get; set; }
        public Nullable<System.DateTime> AdvDate { get; set; }
        public string DocumentUrl { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string PdfUrl { get; set; }
        public string CategoryName { get; set; }
        public string SubCategoryName { get; set; }
    }
}
