//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwADV_RedesignForAdmin
    {
        public string SubjectEng { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string SubjectHin { get; set; }
        public long AdvId { get; set; }
        public bool IsApproved { get; set; }
        public bool IsUploaded { get; set; }
        public bool IsRejected { get; set; }
        public string IsUploadedStatus { get; set; }
        public string IsApprovedStatus { get; set; }
        public long RedesignPlatformUserLookupId { get; set; }
        public int RequestedStatus { get; set; }
    }
}
