//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwADV_AchievementAttachments
    {
        public long AttachmentsId { get; set; }
        public int AchievementId { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public int CategoryCode { get; set; }
        public string Department { get; set; }
        public string DepartmentHindi { get; set; }
        public string Path { get; set; }
        public Nullable<long> AchievementSubCategoryCode { get; set; }
    }
}
