//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClientModuleDetail
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public string Password { get; set; }
        public string ClientId { get; set; }
        public string SSOID { get; set; }
        public string moduleIds { get; set; }
        public string modulename { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
    }
}
