//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCMO_DistrictByOffice
    {
        public long OfficeId { get; set; }
        public Nullable<int> BlockCode { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public Nullable<int> OfficeCode { get; set; }
        public string OfficeName { get; set; }
        public string OfficeNameHindi { get; set; }
        public Nullable<int> TehsilCode { get; set; }
        public string BlockName { get; set; }
        public string BlockNameHindi { get; set; }
        public string TehsilTitle { get; set; }
        public string TehsilTitleHindi { get; set; }
        public string DistrictTitle { get; set; }
        public string DistrictTitleHindi { get; set; }
    }
}
