//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwComplaintActionHistory
    {
        public long Id { get; set; }
        public long ComplaintEntryId { get; set; }
        public string AttachmentURL { get; set; }
        public string Comment { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserName { get; set; }
        public string UserType { get; set; }
        public string UserTypeTitle { get; set; }
        public string FromBaseUserType { get; set; }
        public string FromBaseUserTypeTitle { get; set; }
        public string FromUser { get; set; }
    }
}
