//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCPT_PreviousGovtEntryParameterMapping
    {
        public long MappingId { get; set; }
        public Nullable<int> PreviousGovtId { get; set; }
        public string PhysicalValue { get; set; }
        public string FinancialValue { get; set; }
        public string YearName { get; set; }
        public Nullable<int> YearCode { get; set; }
    }
}
