//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCPT_EbookletParameters
    {
        public Nullable<long> parameterCode { get; set; }
        public string Description1 { get; set; }
        public string YearName { get; set; }
        public string FinancialValue { get; set; }
        public string PhysicalValue { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<int> KPICategoryCode { get; set; }
        public Nullable<bool> IsDepartment { get; set; }
        public Nullable<bool> IsAplicableToAllDpt { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> YearGrandTotalCode { get; set; }
        public Nullable<bool> IsEbookletReport { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<long> ParameterCategoryCode { get; set; }
        public Nullable<long> ParameterId { get; set; }
    }
}
