//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCPT_CurrentGovtEntryParameterMapping
    {
        public long MappingId { get; set; }
        public Nullable<int> CurrentGovtEntryId { get; set; }
        public Nullable<long> ParameterCode { get; set; }
        public string PhysicalParameter { get; set; }
        public string FinancialParameter { get; set; }
        public string physicalUnitName { get; set; }
        public string FinancialUnitName { get; set; }
        public string PhysicalValue { get; set; }
        public string FinancialValue { get; set; }
        public Nullable<int> KPICategoryCode { get; set; }
        public Nullable<bool> IsFinancial { get; set; }
        public Nullable<bool> IsPhysical { get; set; }
        public Nullable<bool> IsDistrict { get; set; }
        public Nullable<bool> IsDepartment { get; set; }
        public string KPICategoryName { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
    }
}
