//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDepartmentMaster
    {
        public int DepartmentId { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public string DepartmentShortTitle { get; set; }
        public string DepartmentShortTitleHindi { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string DepartmentAddress { get; set; }
        public string DepartmentAddressHindi { get; set; }
        public Nullable<bool> DepartmentIsActive { get; set; }
        public Nullable<bool> DepartmentIsDeleted { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public string AdmDepartmentTitleHindi { get; set; }
        public string GroupTitle { get; set; }
        public string GroupTitleHindi { get; set; }
        public string DistrictTitle { get; set; }
        public string DistrictTitleHindi { get; set; }
        public Nullable<int> DepartmentCategoryCode { get; set; }
        public string DepartmentCategoryName { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> DepartmentMenuCount { get; set; }
        public Nullable<int> DepartmentSectionCount { get; set; }
        public Nullable<int> DepartmentSubMenuCount { get; set; }
    }
}
