//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDept_DepartmentSubMenu
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<long> DepartmentMainMenuCode { get; set; }
        public string ModuleName { get; set; }
        public Nullable<long> ModuleCategoryCode { get; set; }
        public string IconImage { get; set; }
        public Nullable<bool> IsSubMenu { get; set; }
        public Nullable<long> DepartmentSubMenuCode { get; set; }
        public string DisplayNameEnglish { get; set; }
        public string DisplayNameHindi { get; set; }
        public Nullable<long> DisplayOrder { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string DepartmentMainMenuName { get; set; }
        public string DepartmentTitle { get; set; }
        public string CreatedByName { get; set; }
        public string ModifiedByName { get; set; }
        public string DepartmentSubSubMenuName { get; set; }
        public string ModuleNameEnglish { get; set; }
        public string ModuleCategoryNameEnglish { get; set; }
    }
}
