//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwGetUserForNotification
    {
        public string UserName { get; set; }
        public string SSOID { get; set; }
        public int UserId { get; set; }
        public string UserEmail { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> User_DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public Nullable<int> OfficeCode { get; set; }
        public string OfficeName { get; set; }
    }
}
