//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwHelpDocument
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<long> TypeCode { get; set; }
        public string Url { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string TypeName { get; set; }
        public string BlankDocUrl { get; set; }
        public string modifiedByName { get; set; }
        public string SSOID { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string DocumentName { get; set; }
    }
}
