//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJAN_ChiefMinisterProfile
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<int> TitleCode { get; set; }
        public Nullable<int> DesignationCode { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public string Message { get; set; }
        public string MessageHindi { get; set; }
        public string PhotoPath { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string PathUrl { get; set; }
        public string TitleName { get; set; }
        public string TitleNameHindi { get; set; }
        public string DesignationName { get; set; }
        public string DesignationNameHindi { get; set; }
    }
}
