//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJAN_PROJ_MLAConstituencyMaster
    {
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string MAPImagePath { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string MLANameEng { get; set; }
        public string MLANameHindi { get; set; }
        public string MLAPhoto { get; set; }
        public string ShortName { get; set; }
        public string DistrictTitle { get; set; }
        public string ModifiedByName { get; set; }
        public Nullable<int> DesignationCode { get; set; }
        public string DesignationDisplayName { get; set; }
        public string DesignationName { get; set; }
        public string Email { get; set; }
        public string whatsappNumber { get; set; }
        public string FBLink { get; set; }
        public string TwitterLink { get; set; }
        public string DesignationShortName { get; set; }
    }
}
