//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJAN_PROJ_ProjectSchemeCategoryMaster
    {
        public int Id { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> NodalDepartmentCode { get; set; }
        public Nullable<long> ProgramSchemeTypeCode { get; set; }
        public string ProgramSchemeName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string DepartmentTitle { get; set; }
        public string ProgramSchemeTypeName { get; set; }
        public Nullable<int> TotalProjectsAdded { get; set; }
    }
}
