//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJAN_PressRelease
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public Nullable<int> SubCategoryCode { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string GeneralDescription { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<long> DisplayOrder { get; set; }
        public string PDFUrl { get; set; }
        public string ImageUrl { get; set; }
        public string HomePageImageUrl { get; set; }
        public string KeyWords { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<decimal> DIPR_Id { get; set; }
        public Nullable<System.DateTime> PressreleaseDate { get; set; }
        public string DepartmentTitle { get; set; }
        public string DistrictName { get; set; }
        public string ModifiedByName { get; set; }
        public string CategoryNameEnglish { get; set; }
        public string CategoryNameHindi { get; set; }
        public string SubCategoryNameEnglish { get; set; }
        public string SubCategoryNameHindi { get; set; }
    }
}
