//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJAN_PressRelease_Front
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<int> CategoryCode { get; set; }
        public Nullable<int> SubCategoryCode { get; set; }
        public string GeneralDescription { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public Nullable<long> DisplayOrder { get; set; }
        public string PDFUrl { get; set; }
        public string ImageUrl { get; set; }
        public string HomePageImageUrl { get; set; }
        public string KeyWords { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CategoryName { get; set; }
        public string CategoryNameHindi { get; set; }
        public string SubCategoryName { get; set; }
        public string SubCategoryNameHindi { get; set; }
        public string PressReleaseLevel { get; set; }
        public string PressReleaseLevelHindi { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public string DistrictNameHindi { get; set; }
        public string DistrictName { get; set; }
        public string VIPCategory { get; set; }
        public string VIPCategoryHindi { get; set; }
        public string VIPPersion { get; set; }
        public string VIPPersionHindi { get; set; }
        public string Attachments { get; set; }
        public string ImageAttachments { get; set; }
        public Nullable<long> CommonCategoryCode { get; set; }
        public string PressReleaseTime { get; set; }
        public Nullable<System.DateTime> PressreleaseDate { get; set; }
    }
}
