//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLookupMaster
    {
        public long LookupId { get; set; }
        public string Lookup { get; set; }
        public string Description { get; set; }
        public Nullable<int> LookupTypeId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> LookupIsRef { get; set; }
        public string LookupType { get; set; }
        public Nullable<bool> LookupTypeIsRef { get; set; }
    }
}
