//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwMonitoringParameterLookupType
    {
        public string lookuptypeName { get; set; }
        public string lookuptypeNameinHindi { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public string TypeCode { get; set; }
        public long Id { get; set; }
    }
}
