//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwODR_OrderRelatedTo
    {
        public long Id { get; set; }
        public long OrderEntryID { get; set; }
        public string ModuleId { get; set; }
        public string ModuleName { get; set; }
        public string DepartmentId { get; set; }
        public string DepartmentName { get; set; }
        public string YearValue { get; set; }
        public string YearText { get; set; }
        public Nullable<long> RelatedToParameterID { get; set; }
        public string Projecthdrid { get; set; }
        public string ResultModuleName { get; set; }
        public string ResultYear { get; set; }
        public string ResultDepartmentId { get; set; }
        public string ResultDepartmentName { get; set; }
        public string ParaNo { get; set; }
        public string FileNumber { get; set; }
        public string ResultDescription { get; set; }
        public Nullable<int> CMISNewTransCoreId { get; set; }
    }
}
