//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwODR_GNRT_OrderGenerateHindiEnglish
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrderNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectForm { get; set; }
        public string ReferenceLink { get; set; }
        public bool IsWithinSecretariat { get; set; }
        public Nullable<long> IssueBy { get; set; }
        public string IndividualBeneficiaryScheme { get; set; }
        public Nullable<bool> IsOldOrder { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string SearchCriteria { get; set; }
        public string FileNumber { get; set; }
        public Nullable<long> LinkToScheme { get; set; }
        public string Subject { get; set; }
        public string Reference { get; set; }
        public string Context { get; set; }
        public string Content { get; set; }
        public Nullable<long> AuthoritySignatureCode { get; set; }
        public Nullable<long> CCSignatureCode { get; set; }
        public string OrdGenrateRemarks { get; set; }
        public string AddressTo { get; set; }
        public Nullable<bool> IsHindi { get; set; }
        public Nullable<bool> IsSaveAsDraft { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public string ESignedFinalUrl { get; set; }
        public string ESignedUrl1 { get; set; }
        public string ESignedUrl2 { get; set; }
        public string ESignedUrl3 { get; set; }
        public string ESignedUrl4 { get; set; }
        public string ESignedUrl5 { get; set; }
        public string UINumber { get; set; }
        public Nullable<long> CCCategoryCode { get; set; }
        public Nullable<bool> IsByOrderOfGovernor { get; set; }
        public string IsByOrderOfGovernortext { get; set; }
        public Nullable<int> SubTypeCode { get; set; }
        public string SubTypeName { get; set; }
        public string SubTypeNameHindi { get; set; }
        public string LinkToSchemeName { get; set; }
        public string LinkToSchemeNameHindi { get; set; }
        public string AuthoritySignatureDesignationName { get; set; }
        public string AuthoritySignatureDesignationHindi { get; set; }
        public string AuthoritySignatureName { get; set; }
        public string AuthoritySignatureNameHindi { get; set; }
        public string CCSignatureDesignation { get; set; }
        public string CCSignatureDesignationHindi { get; set; }
        public string CCSignatureName { get; set; }
        public string CCSignatureNameHindi { get; set; }
        public string TypeName { get; set; }
        public string TypeNameHindi { get; set; }
        public string IssueByName { get; set; }
        public string IssueByNameHindi { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public string DepartmentEffectedIds { get; set; }
        public string DepartmentEffectedName { get; set; }
        public string SectorIds { get; set; }
        public string SectorName { get; set; }
        public string ReferenceText { get; set; }
        public string Attachments { get; set; }
        public string DepartmentEffectedNameHindi { get; set; }
        public string SectorNameHindi { get; set; }
        public string DispatchNumber { get; set; }
        public string FileWithDispatchNumber { get; set; }
        public string Address1 { get; set; }
        public string AddressHindi1 { get; set; }
        public string Address2 { get; set; }
        public string AddressHindi2 { get; set; }
        public string Address3 { get; set; }
        public string AddressHindi3 { get; set; }
        public string FooterLine1 { get; set; }
        public string FooterLineHindi1 { get; set; }
        public string FooterLine2 { get; set; }
        public string FooterLineHindi2 { get; set; }
        public string Logo1 { get; set; }
        public string Logo2 { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public string WithinSecretariat { get; set; }
    }
}
