//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwODR_OrderDetails
    {
        public long Id { get; set; }
        public Nullable<long> Type { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OrderNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> EffectForm { get; set; }
        public string SearchCriteria { get; set; }
        public string FileNumber { get; set; }
        public Nullable<long> LinkToScheme { get; set; }
        public string linktoschemeName { get; set; }
        public string ReferenceLink { get; set; }
        public Nullable<long> IssueBy { get; set; }
        public string IndividualBeneficiaryScheme { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public string BeneficiaryCategoryIds { get; set; }
        public string BeneficiaryCategoryName { get; set; }
        public string BeneficiaryCategoryNameHindi { get; set; }
        public string DepartmentEffectedIds { get; set; }
        public string DepartmentEffectedName { get; set; }
        public string DepartmentEffectedNameHindi { get; set; }
        public string SectorIds { get; set; }
        public string SectorName { get; set; }
        public string SectorNameHindi { get; set; }
        public string MediaUrls { get; set; }
        public string MediaNames { get; set; }
        public string MediaIsAnnexure { get; set; }
        public string IssueByName { get; set; }
        public string TypeName { get; set; }
        public string TypeNameHindi { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<bool> IsOldOrder { get; set; }
        public string BenificiarySchemeIds { get; set; }
        public Nullable<long> CCCategoryCode { get; set; }
        public Nullable<bool> IsByOrderOfGovernor { get; set; }
        public string IsByOrderOfGovernortext { get; set; }
        public Nullable<bool> IsAnnexure { get; set; }
        public Nullable<int> SubTypeCode { get; set; }
        public string SubTypeName { get; set; }
        public string SubTypeNameHindi { get; set; }
        public string ESignedFinalUrl { get; set; }
        public Nullable<int> DistrictCode { get; set; }
        public string districtName { get; set; }
        public Nullable<int> OfficeCode { get; set; }
        public string OfficeName { get; set; }
        public string ModifiedName { get; set; }
        public Nullable<int> TypeDocumentNoMandatory { get; set; }
        public Nullable<bool> TypeDateMandatory { get; set; }
    }
}
