//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPageMaster
    {
        public long PageId { get; set; }
        public long PageCode { get; set; }
        public string PageTitle { get; set; }
        public string ApplicationCode { get; set; }
        public string ApplicationTitle { get; set; }
        public int PageTypeCode { get; set; }
        public string PageTypeName { get; set; }
        public int MenuCode { get; set; }
        public string MenuTitle { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<bool> IsConnectWithCMIS { get; set; }
        public Nullable<bool> IsVisibleForPermission { get; set; }
    }
}
