//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPhotoVedioGallery
    {
        public int GalleryCode { get; set; }
        public string Type { get; set; }
        public int TypeCode { get; set; }
        public string Caption { get; set; }
        public string Url { get; set; }
        public string UploadType { get; set; }
        public string Thumbnail { get; set; }
        public Nullable<long> SchemeCode { get; set; }
        public string SchemeName { get; set; }
        public string SchemeNameHindi { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
