//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSCM_ContactPersonDetail
    {
        public string NodelOfficerName { get; set; }
        public string MobileNo { get; set; }
        public string Designation { get; set; }
        public string SsoId { get; set; }
        public string EmailId { get; set; }
        public long Id { get; set; }
        public Nullable<long> AdminDepartmentCode { get; set; }
        public Nullable<long> NodelDepartmentCode { get; set; }
        public long schemeId { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public string AdmDepartmentTitle { get; set; }
        public string AdmDepartmentTitleHindi { get; set; }
        public string DistrictTitle { get; set; }
        public string DistrictTitleHindi { get; set; }
        public string TehsilTitle { get; set; }
        public string TehsilTitleHindi { get; set; }
        public string BlockName { get; set; }
        public string BlockNameHindi { get; set; }
        public string Name { get; set; }
        public string NameHindi { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Address { get; set; }
    }
}
