//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSCM_GetSchemeForPriorityListView
    {
        public Nullable<long> RowNumber { get; set; }
        public long Id { get; set; }
        public string NameEnglish { get; set; }
        public int NodelDepartmentCode { get; set; }
        public bool IsActive { get; set; }
        public long PriorityInList { get; set; }
        public int ItemOrder { get; set; }
        public Nullable<bool> IsFlagShipScheme { get; set; }
        public string FlagshipImage { get; set; }
    }
}
