//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchemeLookup
    {
        public long SchemeId { get; set; }
        public string ShortNameHindi { get; set; }
        public string NameHindi { get; set; }
        public string ShortNameEnglish { get; set; }
        public string NameEnglish { get; set; }
        public Nullable<long> AdminDepartmentCode { get; set; }
        public Nullable<long> DepartmentCode { get; set; }
        public string NodelOfficerName { get; set; }
        public string EmailId { get; set; }
        public string SsoId { get; set; }
        public string DepartmentTitle { get; set; }
    }
}
