//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSCM_SchemeFrontEndDetails
    {
        public long Id { get; set; }
        public long VisitorCount { get; set; }
        public int PageType { get; set; }
        public string ShortNameHindi { get; set; }
        public string NameHindi { get; set; }
        public string ShortNameEnglish { get; set; }
        public string NameEnglish { get; set; }
        public string Description { get; set; }
        public string ModeOfDisbursmentName { get; set; }
        public string ModeOfDisbursmentNameinHindi { get; set; }
        public Nullable<long> OwnedBy { get; set; }
        public string OwnedByName { get; set; }
        public string OwnedByNameinhindi { get; set; }
        public string ApplyForSchemeName { get; set; }
        public string ApplyForSchemeNameinhindi { get; set; }
        public string MadeOfApplingName { get; set; }
        public string MadeOfApplingNameinhindi { get; set; }
        public Nullable<decimal> OwnedBySate { get; set; }
        public Nullable<decimal> OwnedByCenter { get; set; }
        public Nullable<long> IsListedRGDPSAct { get; set; }
        public string IsListedRGDPSActName { get; set; }
        public Nullable<decimal> DeliveryTimeInDays { get; set; }
        public string IsListedRGDPSActNameinhindi { get; set; }
        public Nullable<long> DesignatedOfficerReceivingDetailCode { get; set; }
        public string DesignatedOfficerReceivingDetailName { get; set; }
        public string DesignatedOfficerReceivingDetailNameinhindi { get; set; }
        public Nullable<long> FirstAppeallateCode { get; set; }
        public string FirstAppeallateName { get; set; }
        public string FirstAppeallateNameinhindi { get; set; }
        public Nullable<long> SecondAppeallateCode { get; set; }
        public string SecondAppeallateName { get; set; }
        public string SecondAppeallateNameinhindi { get; set; }
        public Nullable<long> ApplyForScheme { get; set; }
        public Nullable<decimal> TimeOfValidationInMonth { get; set; }
        public Nullable<long> ExpiredOn { get; set; }
        public string ExpiredOnName { get; set; }
        public string ExpiredOnNameinhindi { get; set; }
        public Nullable<long> DurationType { get; set; }
        public string DurationTypeName { get; set; }
        public string DurationTypeNameHindi { get; set; }
        public Nullable<System.DateTime> ExpriedOnDate { get; set; }
        public Nullable<decimal> ExpriedDurationInMonth { get; set; }
        public Nullable<long> MadeOfAppling { get; set; }
        public Nullable<long> MadeOfApplingOnlineBoth { get; set; }
        public string MadeOfApplingOnlineBothName { get; set; }
        public string MadeOfApplingOnlineBothNameinhindi { get; set; }
        public string DepartmentWebsiteUrl { get; set; }
        public Nullable<long> IsServiceFees { get; set; }
        public string IsServiceFeesName { get; set; }
        public string IsServiceFeesNameinhindi { get; set; }
        public Nullable<long> HowToPayFeeCode { get; set; }
        public string HelplineNo { get; set; }
        public Nullable<long> DelivarebleCode { get; set; }
        public string DelivarebleName { get; set; }
        public string DelivarebleNameinhindi { get; set; }
        public string deliveryPaymentDetail { get; set; }
        public Nullable<long> ModeOfDisbursmentCode { get; set; }
        public string ModeOfDisbursment { get; set; }
        public Nullable<long> PaymentDisbursmentFrequency { get; set; }
        public string PaymentDisbursmentFrequencyName { get; set; }
        public string PaymentDisbursmentFrequencyNameinhindi { get; set; }
        public Nullable<long> PaymentDisbursmentFrequencyInstallments { get; set; }
        public string PaymentDisbursmentFrequencyInstallmentsName { get; set; }
        public string PaymentDisbursmentFrequencyInstallmentsNameinhindi { get; set; }
        public string PaymentDisbursmentFrequencyTillAPeriod { get; set; }
        public Nullable<int> NumberOfInstallments { get; set; }
        public string BeneficiaryPdf { get; set; }
        public string ItemDetails { get; set; }
        public string DocumentCertificateLicenseDocument { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> Code { get; set; }
        public Nullable<decimal> ServiceFeeAmount { get; set; }
        public string Scheme_URL { get; set; }
        public string SearchKeyWordOfDetails { get; set; }
        public string SearchKeyWordOfExecution { get; set; }
        public string SearchKeyWordOfEligible { get; set; }
        public string SearchKeyWordOfHowToApply { get; set; }
        public string SearchKeyWordOfBeneficiaryGet { get; set; }
        public string SearchKeyWordOfOtherDocument { get; set; }
        public string Benificiarytext { get; set; }
        public string EligiblityText { get; set; }
        public string HowToApplyText { get; set; }
        public string WhatWillBeneficiaryGet { get; set; }
        public string StartDate { get; set; }
        public string Logo { get; set; }
        public string Designation { get; set; }
        public string BannerImage { get; set; }
        public string WebsiteUrl { get; set; }
        public string MobileAppIcon { get; set; }
        public string MobileAppUrl { get; set; }
        public Nullable<bool> IsbeneficiaryText { get; set; }
        public Nullable<bool> IsEligibityText { get; set; }
        public Nullable<bool> IsHowToApply { get; set; }
        public Nullable<bool> IsWhatWillBeneficiaryGet { get; set; }
        public string DepartmentTitle { get; set; }
        public string DepartmentTitleHindi { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string BeneficiaryCategoryIds { get; set; }
        public string BeneficiaryCategoryName { get; set; }
        public string BeneficiaryCategoryNameinHindi { get; set; }
        public string DistrictIds { get; set; }
        public string DistrictName { get; set; }
        public string DistrictNameinHindi { get; set; }
        public string TypeIds { get; set; }
        public string TypeName { get; set; }
        public string TypeNameinHindi { get; set; }
        public string ModeOfDeliveryIds { get; set; }
        public string ModeOfDeliveryName { get; set; }
        public string ModeOfDeliveryNameinHindi { get; set; }
        public string CasteCategoryIds { get; set; }
        public string CasteCategoryName { get; set; }
        public string CasteCategoryNameinHindi { get; set; }
        public string ProgramAreaIds { get; set; }
        public string ProgramAreaName { get; set; }
        public string ProgramAreaNameinHindi { get; set; }
        public Nullable<int> CategoryMasterCount { get; set; }
        public Nullable<int> CategoryLookUpCount { get; set; }
        public Nullable<int> FaqCount { get; set; }
        public string HowToPayFeeName { get; set; }
        public string HowToPayFeeNameinhindi { get; set; }
        public string ModeofApplicationIds { get; set; }
        public string ModeofApplicationName { get; set; }
        public string ModeofApplicationHindiName { get; set; }
        public string ModeofDisbursementIds { get; set; }
        public string ModeofDisbursementName { get; set; }
        public string ModeofDisbursementHindiName { get; set; }
        public string HowtoPayFeeRemarks { get; set; }
        public string URLofDataofBeneficiaryonJansoochnaPortal { get; set; }
        public bool schemeIsLock { get; set; }
        public Nullable<long> SchemeOrServiceCode { get; set; }
        public string SchemeOrServiceName { get; set; }
        public string SchemeOrServiceNameHindi { get; set; }
        public string ServiceFeePdf { get; set; }
    }
}
