//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSchememasterlookup
    {
        public long SchemeId { get; set; }
        public string SchemeName { get; set; }
        public Nullable<long> DepartmentCode { get; set; }
        public Nullable<long> BeneficiaryCode { get; set; }
    }
}
