//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSCM_SetSchemeNameForUser
    {
        public string NameEnglish { get; set; }
        public string NameHindi { get; set; }
        public string UserName { get; set; }
        public long Id { get; set; }
        public bool IsActive { get; set; }
        public int Department { get; set; }
        public long AdminDepartment { get; set; }
        public Nullable<int> PageType { get; set; }
        public string schemePageTypeName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
