//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwServiceLookup
    {
        public int ServiceId { get; set; }
        public string PortalName { get; set; }
        public string ServiceName { get; set; }
        public string DepartmentCode { get; set; }
        public string ServerIP { get; set; }
        public string Frequency { get; set; }
        public string DepartmentTitle { get; set; }
    }
}
