//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserWhichHasDefaultPermission
    {
        public int UserTypeId { get; set; }
        public string UserType { get; set; }
        public string UserTypeTitle { get; set; }
        public long PageCode { get; set; }
    }
}
