//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserListWithDepartmentCode
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string SSOID { get; set; }
        public string CreatedUserContact { get; set; }
        public int DepartmentCode { get; set; }
    }
}
