//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserBlockLookup
    {
        public int BlockCode { get; set; }
        public string BlockTitle { get; set; }
        public string BlockTitleHindi { get; set; }
        public int DistrictCode { get; set; }
        public string DistrictTitle { get; set; }
        public int UserId { get; set; }
    }
}
