//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserDivisionLookUp
    {
        public int DivisionCode { get; set; }
        public string DivisionTitle { get; set; }
        public string DivisionTitleHindi { get; set; }
        public string DivisionShortTitle { get; set; }
        public string DivisionShortTitleHindi { get; set; }
        public int UserId { get; set; }
    }
}
