//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMOWebApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwVC_Details
    {
        public long Id { get; set; }
        public Nullable<long> Code { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<long> ChairPersonCategoryCode { get; set; }
        public Nullable<long> ChairPersonCode { get; set; }
        public Nullable<long> TypeCode { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public Nullable<decimal> NoOfHours { get; set; }
        public Nullable<decimal> NoOfMinutes { get; set; }
        public string ChairPersonCategoryName { get; set; }
        public string ChairPersonName { get; set; }
        public string TypeName { get; set; }
        public Nullable<int> ParticipantDisplayOrder { get; set; }
        public Nullable<int> ParticipantCategoryDisplayOrder { get; set; }
        public Nullable<long> VCCategoryCode { get; set; }
        public string VCCategoryName { get; set; }
        public Nullable<int> DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
    }
}
